#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
tmpdir="$(mktemp -d "${TMPDIR:-/tmp}/qge-noesis-contract.XXXXXX")"
trap 'rm -rf "$tmpdir"' EXIT

grep -q 'stream_mouse="${QGE_STREAM_MOUSE:-0}"' "$repo_root/tools/quake_graphics_stream.sh"
grep -q 'stream_display="${QGE_STREAM_DISPLAY:-}"' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq 'app_bin="${QGE_STREAM_APP_BIN:-$repo_root/QuantumQuake.app/Contents/MacOS/quantum_quake}"' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq '"app_bin": $(json_string "$app_bin")' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq 'run_args+=(-nomouse)' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq 'run_args=(-nolauncher -basedir "$basedir" "${video_args[@]}")' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq 'arguments = [[QuakeArguments alloc] initWithArguments:gArgv + 1 count:gArgc - 1];' "$repo_root/quake/MacOSX/AppController.m"
grep -Fq 'if ([arguments argument:@"-nolauncher"] != nil)' "$repo_root/quake/MacOSX/AppController.m"
grep -Fq '[self launchQuakeUsingLauncherControls:NO];' "$repo_root/quake/MacOSX/AppController.m"
grep -Fq '[self launchQuakeUsingLauncherControls:YES];' "$repo_root/quake/MacOSX/AppController.m"
grep -Fq '[quakeArgs removeObjectAtIndex:i];' "$repo_root/quake/MacOSX/QuakeArguments.m"
grep -Fq "printf 'APPL????' > \$(APP_CONTENTS)/PkgInfo" "$repo_root/Makefile"
grep -Fq 'exact `APPL????` `PkgInfo` record' "$repo_root/docs/qge_agent_stream.md"
grep -Fq 'video_args+=(-display "$stream_display")' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq 'open "${open_args[@]}" --args -ApplePersistenceIgnoreState YES "${run_args[@]}" -condebug >>"$open_log_file" 2>&1' "$repo_root/tools/quake_graphics_stream.sh"
grep -q 'startup_issue="gl_context_failed"' "$repo_root/tools/quake_graphics_stream.sh"
grep -q 'startup_issue="open_failed_\$open_status"' "$repo_root/tools/quake_graphics_stream.sh"
grep -q 'latest_icc_evidence.txt' "$repo_root/tools/quake_graphics_stream.sh"
grep -q 'write_latest_stream_pointers' "$repo_root/tools/quake_graphics_stream.sh"
grep -q 'recover_latest_trace_pointer' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq 'if [[ "$trace" == "1" && -s "$trace_file" ]]; then' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq 'replay_trace="${QGE_STREAM_REPLAY_TRACE:-${QGE_REPLAY_TRACE_PATH:-}}"' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq 'run_args+=(-qgereplay "$replay_trace" -qgereplaystrict "$replay_strict")' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq '"trace_file": $(json_string "$replay_trace")' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq 'QGE_CommandLineReplayPath' "$repo_root/quake/Quake/qge_hooks.c"
grep -Fq 'QGE_REPLAY_TRACE_PATH' "$repo_root/quake/Quake/qge_hooks.c"
grep -Fq 'QGE_REPLAY_STRICT' "$repo_root/quake/Quake/qge_hooks.c"
grep -Fq 'qge_quantum_runtime_load_replay_trace(rt, replay_path)' "$repo_root/quake/Quake/qge_hooks.c"
grep -Fq 'QGE_ENTROPY_SOURCE_REPLAY' "$repo_root/qge/qge_rng.c"
grep -Fq 'QGE_STREAM_REPLAY_TRACE' "$repo_root/docs/qge_agent_stream.md"
grep -q 'find "$quake_stream_root" -mindepth 2 -maxdepth 2' "$repo_root/tools/quake_graphics_stream.sh"
grep -q 'latest non-empty trace file' "$repo_root/docs/qge_agent_stream.md"
grep -q 'repairs it from the newest existing non-empty' "$repo_root/docs/qge_agent_stream.md"
grep -q 'QGE_ALIAS_VIEWMODEL_BRIGHTNESS' "$repo_root/quake/Quake/qge_hooks.c"
grep -q '#define QGE_ALIAS_VIEWMODEL_BRIGHTNESS 0.19f' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_ALIAS_VIEWMODEL_SHADE_GAIN' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_ALIAS_VIEWMODEL_NORMAL_SHADE_BASE' "$repo_root/quake/Quake/qge_hooks.c"
grep -q '#define QGE_ALIAS_VIEWMODEL_NORMAL_SHADE_BASE 0.78f' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_ALIAS_VIEWMODEL_EDGE_SCALE' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_ALIAS_VIEWMODEL_EDGE_STRIDE_MASK' "$repo_root/quake/Quake/qge_hooks.c"
grep -q '#define QGE_ALIAS_VIEWMODEL_EDGE_STRIDE_MASK 127' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_ALIAS_ENTITY_EDGE_STRIDE_MASK' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_ALIAS_VIEWMODEL_SHADE_MIN' "$repo_root/docs/qge_agent_stream.md"
grep -q 'alias-normal shade' "$repo_root/docs/qge_agent_stream.md"
grep -q 'edge cadence' "$repo_root/docs/qge_agent_stream.md"
grep -q 'timeout_seconds="${QGE_STREAM_TIMEOUT_SECONDS:-}"' "$repo_root/tools/quake_graphics_stream.sh"
grep -q 'normalize_positive_int' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq 'width="$(normalize_positive_int "$width" 800)"' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq 'render_res="$(normalize_positive_int "$render_res" 1024)"' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq 'sound="$(normalize_bool "$sound")"' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq 'trace="$(normalize_bool "$trace")"' "$repo_root/tools/quake_graphics_stream.sh"
grep -q 'trace_status="not_requested"' "$repo_root/tools/quake_graphics_stream.sh"
grep -q '"trace_status":' "$repo_root/tools/quake_graphics_stream.sh"
grep -q '"trace_bytes": \$trace_bytes' "$repo_root/tools/quake_graphics_stream.sh"
grep -q 'trace_status.*not_requested' "$repo_root/docs/qge_agent_stream.md"
grep -q '"frames_captured": \$manifest_frame_count' "$repo_root/tools/quake_graphics_stream.sh"
grep -q '"run": {' "$repo_root/tools/quake_graphics_stream.sh"
grep -q '"startup_issue":' "$repo_root/tools/quake_graphics_stream.sh"
grep -q 'run.status.*run.success.*run.startup_issue' "$repo_root/docs/qge_agent_stream.md"
grep -q 'agent_stream_run_status' "$repo_root/tools/quake_graphics_stream.sh"
grep -q 'agent_stream_run_success' "$repo_root/tools/quake_graphics_stream.sh"
grep -q 'agent_stream_startup_issue' "$repo_root/tools/quake_graphics_stream.sh"
grep -q 'agent_stream_trace_status' "$repo_root/tools/quake_graphics_stream.sh"
grep -q 'agent_trace_file' "$repo_root/tools/quake_graphics_stream.sh"
grep -q 'run outcome, trace status' "$repo_root/docs/qge_agent_stream.md"
grep -q 'perf_max_average_ms="${QGE_PERF_MAX_AVERAGE_MS:-}"' "$repo_root/tools/quake_graphics_stream.sh"
grep -q 'qge_perf_summary.py' "$repo_root/tools/quake_graphics_stream.sh"
grep -q '"performance": {' "$repo_root/tools/quake_graphics_stream.sh"
grep -q 'agent_stream_perf_status' "$repo_root/tools/quake_graphics_stream.sh"
grep -q 'agent_perf_summary_file' "$repo_root/tools/quake_graphics_stream.sh"
grep -q 'QGE_PERF_MAX_AVERAGE_MS' "$repo_root/docs/qge_agent_stream.md"
grep -Fq 'QGE_LauncherProbe("SDLMain"' "$repo_root/quake/MacOSX/SDLMain.m"
grep -Fq 'QGE_LauncherProbe("AppController"' "$repo_root/quake/MacOSX/AppController.m"
grep -Fq 'QGE_LauncherProbe("QuakeArguments"' "$repo_root/quake/MacOSX/QuakeArguments.m"
grep -Fq 'QGE_LauncherProbe("QuakeArgument"' "$repo_root/quake/MacOSX/QuakeArgument.m"
grep -Fq 'QGE_LauncherProbe("ScreenInfo"' "$repo_root/quake/MacOSX/ScreenInfo.m"
grep -q 'QGE launcher probe target=SDLApplication' "$repo_root/quake/MacOSX/SDLApplication.m"
grep -q 'launcher probe' "$repo_root/docs/qge_agent_stream.md"
grep -q 'backend_gate_event_count' "$repo_root/tools/qge_perf_summary.py"
grep -q 'runtime_backend_probe_event_count' "$repo_root/tools/qge_perf_summary.py"
grep -q 'runtime_backend_probe_proofs' "$repo_root/tools/qge_perf_summary.py"
grep -q 'runtime_backend_probe_resolved' "$repo_root/tools/qge_perf_summary.py"
grep -q 'qge.native_backend_boundary.v0' "$repo_root/tools/qge_perf_summary.py"
grep -q 'runtime_backend_boundary_status' "$repo_root/tools/qge_perf_summary.py"
grep -q 'backend_gate_event_count' "$repo_root/docs/qge_agent_stream.md"
grep -q 'runtime_backend_probe_event_count' "$repo_root/docs/qge_agent_stream.md"
grep -q 'runtime_backend_probe_proofs' "$repo_root/docs/qge_agent_stream.md"
grep -q 'agent_manifest_summary' "$repo_root/tools/qge_vanilla_capture_matrix.py"
grep -q 'build_moonlab_domain_readiness' "$repo_root/tools/qge_vanilla_capture_matrix.py"
grep -q 'moonlab_authority_ready' "$repo_root/tools/qge_vanilla_capture_matrix.py"
grep -q 'projectile_live_authority' "$repo_root/tools/qge_vanilla_capture_matrix.py"
grep -q 'active_projectiles_max' "$repo_root/tools/qge_vanilla_capture_matrix.py"
grep -q 'render_quantum_workload' "$repo_root/tools/qge_vanilla_capture_matrix.py"
grep -q 'explicit_agent_run_failure' "$repo_root/tools/qge_vanilla_capture_matrix.py"
grep -q 'agent_stream_runs_success' "$repo_root/tools/qge_vanilla_capture_matrix.py"
grep -q 'performance_sidecars_success' "$repo_root/tools/qge_vanilla_capture_matrix.py"
grep -q 'qge_backend_gate_event_count' "$repo_root/tools/qge_vanilla_capture_matrix.py"
grep -q 'qge_runtime_backend_probe_event_count' "$repo_root/tools/qge_vanilla_capture_matrix.py"
grep -q 'qge_runtime_backend_probe_resolved' "$repo_root/tools/qge_vanilla_capture_matrix.py"
grep -q 'qge_perf_summary.json' "$repo_root/tools/quake_graphics_harness.sh"
grep -q 'agent-stream run failure blocks' "$repo_root/docs/qge_agent_stream.md"
grep -q 'agent_stream_runs_success' "$repo_root/tools/qge_publication_pack.py"
grep -q 'agent_stream_manifest_run' "$repo_root/tools/qge_publication_pack.py"
grep -q 'publication_ready_for_complete_claim' "$repo_root/tools/qge_publication_pack.py"
grep -q 'performance_summary' "$repo_root/tools/qge_publication_pack.py"
grep -q 'performance_ok' "$repo_root/tools/qge_publication_pack.py"
grep -q 'vanilla_performance_sidecars_success' "$repo_root/tools/qge_publication_pack.py"
grep -q 'qge_performance_status' "$repo_root/tools/qge_publication_pack.py"
grep -q 'vanilla_performance_ok' "$repo_root/tools/qge_publication_pack.py"
grep -q 'graphics_capture_dir' "$repo_root/tools/qge_publication_pack.py"
grep -q -- '--breadth-evidence' "$repo_root/tools/qge_publication_pack.py"
grep -q 'breadth_ready_for_complete_claim' "$repo_root/tools/qge_publication_pack.py"
grep -q 'breadth_total_runtime_backend_probe_event_count' "$repo_root/tools/qge_publication_pack.py"
grep -q 'breadth_runtime_backend_probe_proofs' "$repo_root/tools/qge_publication_pack.py"
grep -q 'pack copies these run-status fields' "$repo_root/docs/qge_agent_stream.md"
grep -q 'Publication packs use the stream capture for trace/oracle inputs' "$repo_root/docs/qge_agent_stream.md"
grep -q -- '--breadth-evidence' "$repo_root/docs/qge_agent_stream.md"
grep -q 'qge_breadth_evidence_pack_complete' "$repo_root/tools/qge_breadth_evidence.py"
grep -q -- '--min-maps' "$repo_root/tools/qge_breadth_evidence.py"
grep -q 'qge.full_game_map_coverage.v0' "$repo_root/tools/qge_breadth_evidence.py"
grep -q 'QUAKE_REGISTERED_SINGLE_PLAYER_MAPS' "$repo_root/tools/qge_breadth_evidence.py"
grep -q 'qge_full_game_route_contracts' "$repo_root/tools/qge_breadth_evidence.py"
grep -q 'route_contract_authority_ready_run_count' "$repo_root/tools/qge_breadth_evidence.py"
grep -q 'route_contract_authority_not_ready' "$repo_root/tools/qge_breadth_evidence.py"
grep -q 'qge.asset_inventory.v0' "$repo_root/tools/qge_asset_inventory.py"
grep -q 'QGE_ASSET_INVENTORY' "$repo_root/tools/qge_asset_inventory.py"
grep -q 'qge_registered_asset_inventory_complete' "$repo_root/tools/qge_asset_inventory.py"
grep -q 'invalid_bsp_count' "$repo_root/tools/qge_asset_inventory.py"
grep -q 'qge.registered_asset_intake.v0' "$repo_root/tools/qge_registered_asset_intake.py"
grep -q 'QGE_REGISTERED_ASSET_INTAKE' "$repo_root/tools/qge_registered_asset_intake.py"
grep -q 'qge_registered_asset_intake_plan_recorded' "$repo_root/tools/qge_registered_asset_intake.py"
grep -q 'asset_intake_copies_game_data' "$repo_root/tools/qge_registered_asset_intake.py"
grep -q 'manual_registered_asset_required' "$repo_root/tools/qge_registered_asset_intake.py"
grep -q 'QGE_REGISTERED_ASSET_NO_CANDIDATES' "$repo_root/tools/qge_registered_asset_intake.py"
grep -q 'copy_script_mode' "$repo_root/tools/qge_registered_asset_intake.py"
grep -q 'post_install_verification' "$repo_root/tools/qge_registered_asset_intake.py"
grep -q 'verify_sha256' "$repo_root/tools/qge_registered_asset_intake.py"
grep -q 'qge_full_game_capture_queue.py' "$repo_root/tools/qge_registered_asset_intake.py"
grep -q 'candidate_discovery_command' "$repo_root/tools/qge_registered_asset_intake.py"
grep -q -- '--discover-root' "$repo_root/tools/qge_registered_asset_intake.py"
grep -q -- '--discover-common' "$repo_root/tools/qge_registered_asset_intake.py"
grep -q 'libraryfolders.vdf' "$repo_root/tools/qge_registered_asset_intake.py"
grep -q 'steam_quake_discovery_paths' "$repo_root/tools/qge_registered_asset_intake.py"
grep -q 'discovery_metadata' "$repo_root/tools/qge_registered_asset_intake.py"
grep -q -- '--publication-pack' "$repo_root/tools/qge_registered_asset_intake.py"
grep -q 'bsp_validation_report' "$repo_root/tools/qge_full_game_capture_queue.py"
grep -q 'valid_quake_bsp29' "$repo_root/tools/qge_full_game_capture_queue.py"
grep -q 'qge.full_game_capture_route_contract.v0' "$repo_root/tools/qge_full_game_route_contracts.py"
grep -q 'qge.full_game_route_contract_authority.v0' "$repo_root/tools/qge_full_game_route_contracts.py"
grep -q 'route_contract_authority_audit' "$repo_root/tools/qge_full_game_route_contracts.py"
grep -q 'route_contract_for_map' "$repo_root/tools/qge_full_game_capture_queue.py"
grep -q 'QGE_FULL_GAME_CAPTURE_ROUTE_PROFILE' "$repo_root/tools/qge_full_game_capture_queue.py"
grep -q 'route_contracts_complete' "$repo_root/tools/qge_full_game_capture_queue.py"
grep -q 'route_contracts_complete' "$repo_root/tools/qge_moonlab_full_game_plan.py"
grep -q 'covered_route_contract_authority_complete' "$repo_root/tools/qge_moonlab_full_game_plan.py"
grep -q 'full_game_route_contracts_complete' "$repo_root/tools/qge_moonlab_deployment_gate.py"
grep -q 'covered_route_contract_authority_complete' "$repo_root/tools/qge_moonlab_deployment_gate.py"
grep -q 'qge.full_game_capture_queue.v0' "$repo_root/tools/qge_full_game_capture_queue.py"
grep -q 'QGE_FULL_GAME_CAPTURE_QUEUE' "$repo_root/tools/qge_full_game_capture_queue.py"
grep -q 'run_missing_maps.sh' "$repo_root/tools/qge_full_game_capture_queue.py"
grep -q 'SPECIAL_ROUTE_MAPS' "$repo_root/tools/qge_full_game_capture_queue.py"
grep -q -- '--asset-root' "$repo_root/tools/qge_full_game_capture_queue.py"
grep -q -- '--include-unavailable-assets' "$repo_root/tools/qge_full_game_capture_queue.py"
grep -q 'asset_unavailable_missing_maps' "$repo_root/tools/qge_full_game_capture_queue.py"
grep -q 'blocked_asset_unavailable' "$repo_root/tools/qge_full_game_capture_queue.py"
grep -q 'QGE_STREAM_PLAYER.*noesis' "$repo_root/tools/qge_full_game_capture_queue.py"
grep -q 'QGE_NOESIS_MIN_CAPTURE_WAIT' "$repo_root/tools/qge_full_game_capture_queue.py"
grep -q 'START_HUB_ROUTE_MAPS' "$repo_root/tools/qge_full_game_capture_queue.py"
grep -q 'START_HUB_ROUTE_ENV' "$repo_root/tools/qge_full_game_capture_queue.py"
grep -q 'start_hub_route_authority_smoke' "$repo_root/tools/qge_full_game_capture_queue.py"
grep -q 'special_route_required' "$repo_root/tools/qge_full_game_capture_queue.py"
grep -q 'backend_gate_render_bridge_run_count' "$repo_root/tools/qge_breadth_evidence.py"
grep -q 'runtime_backend_probe_run_count' "$repo_root/tools/qge_breadth_evidence.py"
grep -q 'runtime_backend_probe_resolved_run_count' "$repo_root/tools/qge_breadth_evidence.py"
grep -q 'qge_breadth_evidence_pack' "$repo_root/.icc/completion-oracles.json"
grep -q 'qge_moonlab_hardware_submission_scope' "$repo_root/.icc/completion-oracles.json"
grep -q 'qge_moonlab_hardware_submission_scope_ready' "$repo_root/.icc/completion-oracles.json"
grep -q 'qge_moonlab_full_game_deployment' "$repo_root/.icc/completion-oracles.json"
grep -q 'qge_moonlab_deployment_gate_ready' "$repo_root/.icc/completion-oracles.json"
grep -q 'suppressed_runtime_checks' "$repo_root/.icc/completion-oracles.json"
grep -q 'qge_breadth_evidence.py' "$repo_root/docs/qge_agent_stream.md"
grep -q 'qge_asset_inventory.py' "$repo_root/docs/qge_agent_stream.md"
grep -q 'qge_registered_asset_intake.py' "$repo_root/docs/qge_agent_stream.md"
grep -q -- '--discover-common' "$repo_root/docs/qge_agent_stream.md"
grep -q 'qge_full_game_capture_queue.py' "$repo_root/docs/qge_agent_stream.md"
grep -q 'start_hub_route_authority_smoke' "$repo_root/docs/qge_agent_stream.md"
grep -q 'special_route_required' "$repo_root/docs/qge_agent_stream.md"
grep -q 'asset-unavailable' "$repo_root/docs/qge_agent_stream.md"
grep -q -- '--min-maps' "$repo_root/docs/qge_agent_stream.md"
grep -q 'qge_breadth_evidence_pack' "$repo_root/docs/qge_publishable_results_research.md"
grep -q 'qge_resource_envelope.json' "$repo_root/docs/qge_publishable_results_research.md"
grep -q 'qge_full_game_map_coverage.json' "$repo_root/docs/qge_publishable_results_research.md"
grep -q 'qge_asset_requirements.json' "$repo_root/docs/qge_publishable_results_research.md"
grep -q 'qge_moonlab_full_game_plan.json' "$repo_root/docs/qge_publishable_results_research.md"
grep -q 'qge_native_backend_boundary.json' "$repo_root/docs/qge_publishable_results_research.md"
grep -q 'qge_moonlab_job_specs.json' "$repo_root/docs/qge_publishable_results_research.md"
grep -q 'qge_moonlab_job_results.json' "$repo_root/docs/qge_publishable_results_research.md"
grep -q 'qge_moonlab_replay_plan.json' "$repo_root/docs/qge_publishable_results_research.md"
grep -q 'qge_moonlab_submission_packet.json' "$repo_root/docs/qge_publishable_results_research.md"
grep -q 'qge_moonlab_submission_bundle.json' "$repo_root/docs/qge_publishable_results_research.md"
grep -q 'qge_moonlab_hardware_record_template.json' "$repo_root/docs/qge_publishable_results_research.md"
grep -q 'qge_moonlab_deployment_gate.json' "$repo_root/docs/qge_publishable_results_research.md"
grep -q 'qge_moonlab_deployment_gate.py' "$repo_root/docs/qge_publishable_results_research.md"
grep -q 'qge_moonlab_hardware_ingest.py' "$repo_root/docs/qge_publishable_results_research.md"
grep -q 'qge_moonlab_job_runner.py' "$repo_root/docs/qge_publishable_results_research.md"
grep -q 'qge_asset_inventory.py' "$repo_root/docs/qge_publishable_results_research.md"
grep -q 'qge_registered_asset_intake.py' "$repo_root/docs/qge_publishable_results_research.md"
grep -q 'qge_registered_asset_intake.py' "$repo_root/tools/qge_publication_pack.py"
grep -q 'qge_registered_asset_intake.json' "$repo_root/tools/qge_publication_pack.py"
grep -q 'registered_asset_intake_file' "$repo_root/tools/qge_publication_pack.py"
grep -q 'registered_asset_intake_post_install_capture_queue_command_present' "$repo_root/tools/qge_publication_pack.py"
grep -q -- '--registered-asset-discover-common' "$repo_root/tools/qge_publication_pack.py"
grep -q 'qge_asset_inventory.json' "$repo_root/tools/qge_publication_pack.py"
grep -q 'qge_asset_requirements.py' "$repo_root/tools/qge_publication_pack.py"
grep -q 'qge_asset_requirements.json' "$repo_root/tools/qge_publication_pack.py"
grep -q 'asset_requirements_file' "$repo_root/tools/qge_publication_pack.py"
grep -q 'QGE_ASSET_REQUIREMENTS' "$repo_root/tools/qge_asset_requirements.py"
grep -q 'qge.asset_requirements.v0' "$repo_root/tools/qge_asset_requirements.py"
grep -q 'blocked_missing_registered_assets' "$repo_root/tools/qge_asset_requirements.py"
grep -q 'qge_moonlab_full_game_plan.py' "$repo_root/tools/qge_publication_pack.py"
grep -q 'qge_moonlab_full_game_plan.json' "$repo_root/tools/qge_publication_pack.py"
grep -q 'moonlab_full_game_plan_file' "$repo_root/tools/qge_publication_pack.py"
grep -q 'QGE_MOONLAB_FULL_GAME_PLAN' "$repo_root/tools/qge_moonlab_full_game_plan.py"
grep -q 'qge.moonlab_full_game_deployment_plan.v0' "$repo_root/tools/qge_moonlab_full_game_plan.py"
grep -q 'blocked_asset_unavailable' "$repo_root/tools/qge_moonlab_full_game_plan.py"
grep -q 'whole_game_moonlab_deployment_claimed' "$repo_root/tools/qge_moonlab_full_game_plan.py"
grep -q 'qge_moonlab_deployment_gate.py' "$repo_root/tools/qge_publication_pack.py"
grep -q 'qge_moonlab_deployment_gate.json' "$repo_root/tools/qge_publication_pack.py"
grep -q 'moonlab_deployment_gate_file' "$repo_root/tools/qge_publication_pack.py"
grep -q 'moonlab_deployment_gate_registered_asset_install_script' "$repo_root/tools/qge_publication_pack.py"
grep -q 'moonlab_deployment_gate_post_install_capture_queue_command_present' "$repo_root/tools/qge_publication_pack.py"
grep -q 'QGE_MOONLAB_DEPLOYMENT_GATE' "$repo_root/tools/qge_moonlab_deployment_gate.py"
grep -q 'qge.moonlab_deployment_gate.v0' "$repo_root/tools/qge_moonlab_deployment_gate.py"
grep -q 'whole_game_moonlab_deployment_claim_allowed' "$repo_root/tools/qge_moonlab_deployment_gate.py"
grep -q 'dense_70000_qubit_state_claim_allowed' "$repo_root/tools/qge_moonlab_deployment_gate.py"
grep -q 'asset_remediation_from_intake' "$repo_root/tools/qge_moonlab_deployment_gate.py"
grep -q 'registered_asset_install_script' "$repo_root/tools/qge_moonlab_deployment_gate.py"
grep -q 'registered_asset_discovery_command' "$repo_root/tools/qge_moonlab_deployment_gate.py"
grep -q 'registered_asset_intake_steam_quake_path_count' "$repo_root/tools/qge_moonlab_deployment_gate.py"
grep -q 'post_install_capture_queue_command' "$repo_root/tools/qge_moonlab_deployment_gate.py"
grep -q 'QGE_MOONLAB_JOB_RESULTS' "$repo_root/tools/qge_moonlab_job_runner.py"
grep -q 'QGE_MOONLAB_EXPECTED_RESULTS_MATCH' "$repo_root/tools/qge_moonlab_job_runner.py"
grep -q -- '--expect' "$repo_root/tools/qge_moonlab_job_runner.py"
grep -q -- '--plan-out' "$repo_root/tools/qge_moonlab_job_runner.py"
grep -q -- '--submission-out' "$repo_root/tools/qge_moonlab_job_runner.py"
grep -q 'build_moonlab_job_results' "$repo_root/tools/qge_moonlab_job_runner.py"
grep -q 'build_moonlab_replay_plan' "$repo_root/tools/qge_moonlab_job_runner.py"
grep -q 'qge_moonlab_submission_bundle.py' "$repo_root/tools/qge_publication_pack.py"
grep -q 'qge_moonlab_submission_bundle.json' "$repo_root/tools/qge_publication_pack.py"
grep -q 'moonlab_submission_bundle_file' "$repo_root/tools/qge_publication_pack.py"
grep -q 'QGE_MOONLAB_SUBMISSION_BUNDLE' "$repo_root/tools/qge_moonlab_submission_bundle.py"
grep -q 'qge.moonlab_submission_bundle.v0' "$repo_root/tools/qge_moonlab_submission_bundle.py"
grep -q 'calibration_payload_ready_oracle_transpilation_required' "$repo_root/tools/qge_moonlab_submission_bundle.py"
grep -q 'qf_oracle_kernel_ready_qae_transpilation_required' "$repo_root/tools/qge_moonlab_submission_bundle.py"
grep -q 'qae_observation_zero_ready_grover_schedule_required' "$repo_root/tools/qge_moonlab_submission_bundle.py"
grep -q 'moonlab-circuit v1' "$repo_root/tools/qge_moonlab_submission_bundle.py"
grep -q 'hardware_submission_directly_executable' "$repo_root/tools/qge_moonlab_submission_bundle.py"
grep -q 'qge_moonlab_qae_transpile.py' "$repo_root/tools/qge_publication_pack.py"
grep -q 'qae_moonlab_payload.json' "$repo_root/tools/qge_publication_pack.py"
grep -q 'QGE_MOONLAB_QAE_PAYLOAD' "$repo_root/tools/qge_moonlab_qae_transpile.py"
grep -q 'qge.moonlab_qae_payload.v0' "$repo_root/tools/qge_moonlab_qae_transpile.py"
grep -q 'mlae_observation_distribution_payload' "$repo_root/tools/qge_moonlab_qae_transpile.py"
grep -q 'full_qae_oracle_transpiled' "$repo_root/tools/qge_moonlab_qae_transpile.py"
grep -q 'qge_moonlab_oracle_transpile.py' "$repo_root/tools/qge_publication_pack.py"
grep -q 'qae_moonlab_oracle_kernel.json' "$repo_root/tools/qge_publication_pack.py"
grep -q 'QGE_MOONLAB_QAE_ORACLE_KERNEL' "$repo_root/tools/qge_moonlab_oracle_transpile.py"
grep -q 'qge.moonlab_qae_oracle_kernel.v0' "$repo_root/tools/qge_moonlab_oracle_transpile.py"
grep -q 'bernoulli_lift_qf_oracle_kernel' "$repo_root/tools/qge_moonlab_oracle_transpile.py"
grep -q 'qf_oracle_kernel_transpiled' "$repo_root/tools/qge_moonlab_oracle_transpile.py"
grep -q 'qge_moonlab_qae_observation_transpile.py' "$repo_root/tools/qge_publication_pack.py"
grep -q 'qae_moonlab_observation_zero.json' "$repo_root/tools/qge_publication_pack.py"
grep -q 'QGE_MOONLAB_QAE_OBSERVATION' "$repo_root/tools/qge_moonlab_qae_observation_transpile.py"
grep -q 'qge.moonlab_qae_observation_circuit.v0' "$repo_root/tools/qge_moonlab_qae_observation_transpile.py"
grep -q 'bernoulli_lift_qae_power_zero_observation' "$repo_root/tools/qge_moonlab_qae_observation_transpile.py"
grep -q 'candidate_state_preparation_transpiled' "$repo_root/tools/qge_moonlab_qae_observation_transpile.py"
grep -q 'qge_moonlab_qae_grover_plan.py' "$repo_root/tools/qge_publication_pack.py"
grep -q 'qae_moonlab_grover_schedule_plan.json' "$repo_root/tools/qge_publication_pack.py"
grep -q 'QGE_MOONLAB_QAE_GROVER_PLAN' "$repo_root/tools/qge_moonlab_qae_grover_plan.py"
grep -q 'qge.moonlab_qae_grover_schedule_plan.v0' "$repo_root/tools/qge_moonlab_qae_grover_plan.py"
grep -q 'bernoulli_lift_qae_grover_schedule_control_plane_plan' "$repo_root/tools/qge_moonlab_qae_grover_plan.py"
grep -q 'qae_grover_schedule_blocked_control_plane_body_limit' "$repo_root/tools/qge_moonlab_qae_grover_plan.py"
grep -q 'QGE_MOONLAB_HARDWARE_RESULTS' "$repo_root/tools/qge_moonlab_hardware_ingest.py"
grep -q 'QGE_MOONLAB_HARDWARE_RECORD_TEMPLATE' "$repo_root/tools/qge_moonlab_hardware_ingest.py"
grep -q 'qge.moonlab_hardware_record.v0' "$repo_root/tools/qge_moonlab_hardware_ingest.py"
grep -q -- '--template-out' "$repo_root/tools/qge_moonlab_hardware_ingest.py"
grep -q 'build_hardware_record_template' "$repo_root/tools/qge_moonlab_hardware_ingest.py"
grep -q 'hardware_quantum_advantage_claimed' "$repo_root/tools/qge_moonlab_hardware_ingest.py"
grep -q 'resource_envelope_file' "$repo_root/tools/qge_publication_pack.py"
grep -q 'full_game_map_coverage_file' "$repo_root/tools/qge_publication_pack.py"
grep -q 'qge_full_game_map_coverage.json' "$repo_root/tools/qge_publication_pack.py"
grep -q 'native_backend_boundary_file' "$repo_root/tools/qge_publication_pack.py"
grep -q 'moonlab_job_specs_file' "$repo_root/tools/qge_publication_pack.py"
grep -q 'moonlab_job_results_file' "$repo_root/tools/qge_publication_pack.py"
grep -q 'moonlab_replay_plan_file' "$repo_root/tools/qge_publication_pack.py"
grep -q 'moonlab_hardware_record_template_file' "$repo_root/tools/qge_publication_pack.py"
grep -q 'whole_game_hardware_execution_claimed' "$repo_root/tools/qge_publication_pack.py"
grep -q 'full-game map coverage' "$repo_root/docs/qge_state_of_development.md"
grep -q 'whole-game authority contract' "$repo_root/docs/moonlab_full_quake_port.md"
grep -q 'the entire game runs in Moonlab' "$repo_root/docs/moonlab_full_quake_port.md"
grep -q 'must not be hidden production authority' "$repo_root/docs/moonlab_full_quake_port.md"
grep -q 'qge_vanilla_quake_conformance' "$repo_root/docs/moonlab_full_quake_port.md"
grep -q 'strict runtime matrix complete' "$repo_root/docs/moonlab_full_quake_port.md"
grep -q 'qge_publishable_results_research.md' "$repo_root/docs/README.md"
grep -q 'Quandoom is the closest public comparison point' "$repo_root/docs/qge_publishable_results_research.md"
grep -q 'Real Quantum Computing Bar' "$repo_root/docs/qge_publishable_results_research.md"
grep -q '2\^70000' "$repo_root/docs/qge_publishable_results_research.md"
grep -q '70,000-qubit dense-state fiction is forbidden' "$repo_root/docs/qge_publishable_results_research.md"
grep -q 'qge_vanilla_runtime_complete -> produce_ready_vanilla_capture_matrix' "$repo_root/docs/qge_publishable_results_research.md"
grep -q 'qge_vanilla_runtime_complete' "$repo_root/README.md"
grep -Fq 'frames="$(normalize_positive_int "$frames" 12)"' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq 'waits_per_frame="$(normalize_positive_int "$waits_per_frame" 20)"' "$repo_root/tools/quake_graphics_stream.sh"
grep -q 'capture_wait_override=""' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq 'frames="$(normalize_positive_int "$frames" 1)"' "$repo_root/tools/quake_graphics_harness.sh"
grep -Fq 'waits_per_frame="$(normalize_positive_int "$waits_per_frame" 90)"' "$repo_root/tools/quake_graphics_harness.sh"
grep -Fq 'width="$(normalize_positive_int "$width" 800)"' "$repo_root/tools/quake_graphics_harness.sh"
grep -q -- '--check-deps' "$repo_root/tools/qge_image_metrics.py"
grep -Fq 'python3 tools/qge_image_metrics.py --check-deps' "$repo_root/tools/quake_graphics_harness.sh"
grep -q 'qge_world_frame_metrics.py' "$repo_root/tools/quake_graphics_harness.sh"
grep -q 'QGE_HARNESS_BASELINE_CANDIDATE' "$repo_root/tools/quake_graphics_harness.sh"
grep -q 'QGE_HARNESS_FORCE_WORLD_METRICS' "$repo_root/tools/quake_graphics_harness.sh"
grep -q 'QGE_HARNESS_FIRE_TEST' "$repo_root/tools/quake_graphics_harness.sh"
grep -q 'QGE_HARNESS_SPRITE_TEST' "$repo_root/tools/quake_graphics_harness.sh"
grep -q 'QGE_HARNESS_SND_QUANTUM_SOURCE_AUTHORITY' "$repo_root/tools/quake_graphics_harness.sh"
grep -q 'QGE_HARNESS_PHYSICS_AUTHORITATIVE' "$repo_root/tools/quake_graphics_harness.sh"
grep -q 'QGE_HARNESS_FLATLIGHTSTYLES' "$repo_root/tools/quake_graphics_harness.sh"
grep -q 'QGE_STREAM_FLATLIGHTSTYLES' "$repo_root/tools/quake_graphics_stream.sh"
grep -q 'r_flatlightstyles' "$repo_root/tools/quake_graphics_stream.sh"
grep -q '${mode}_frames' "$repo_root/tools/quake_graphics_harness.sh"
grep -q 'qge.world_frame_metrics.v0' "$repo_root/tools/qge_world_frame_metrics.py"
grep -q 'qge.world_frame_metrics.frames.v0' "$repo_root/tools/qge_world_frame_metrics.py"
grep -q -- '--baseline-candidate' "$repo_root/tools/qge_world_frame_metrics.py"
grep -q 'candidate_temporal_rmse_rgb' "$repo_root/tools/qge_world_frame_metrics.py"
grep -q 'Candidate Drift' "$repo_root/tools/qge_world_frame_metrics.py"
grep -q 'world_upper' "$repo_root/tools/qge_world_frame_metrics.py"
grep -q 'viewmodel' "$repo_root/tools/qge_world_frame_metrics.py"
grep -q 'numpy and Pillow' "$repo_root/docs/qge_agent_stream.md"
grep -q 'QGE_HARNESS_BASELINE_CANDIDATE' "$repo_root/docs/qge_agent_stream.md"
grep -q 'QGE_HARNESS_FORCE_WORLD_METRICS' "$repo_root/docs/qge_agent_stream.md"
grep -q 'QGE_HARNESS_FIRE_TEST' "$repo_root/docs/qge_agent_stream.md"
grep -q 'QGE_HARNESS_FLATLIGHTSTYLES' "$repo_root/docs/qge_agent_stream.md"
grep -q 'world_upper' "$repo_root/docs/qge_agent_stream.md"
grep -q '"timeout_seconds": \$max_seconds' "$repo_root/tools/quake_graphics_stream.sh"
grep -q 'agent_event "process_exit"' "$repo_root/tools/quake_graphics_stream.sh"
grep -q 'startup_issue="process_exit_\$game_status"' "$repo_root/tools/quake_graphics_stream.sh"
grep -q 'stream_mouse="${QGE_STREAM_MOUSE:-0}"' "$repo_root/tools/quake_crash_watch.sh"
grep -q 'stream_display="${QGE_STREAM_DISPLAY:-}"' "$repo_root/tools/quake_crash_watch.sh"
grep -Fq 'run_args+=(-nomouse)' "$repo_root/tools/quake_crash_watch.sh"
grep -Fq 'run_args+=(-display "$stream_display")' "$repo_root/tools/quake_crash_watch.sh"
grep -q 'stream_player="${QGE_STREAM_PLAYER:-noesis}"' "$repo_root/tools/quake_crash_watch.sh"
grep -q 'emit_noesis_player_script' "$repo_root/tools/quake_crash_watch.sh"
grep -q 'normalize_nonnegative_int' "$repo_root/tools/quake_crash_watch.sh"
grep -Fq 'seconds="$(normalize_nonnegative_int "$seconds" 90)"' "$repo_root/tools/quake_crash_watch.sh"
grep -Fq 'width="$(normalize_positive_int "$width" 800)"' "$repo_root/tools/quake_crash_watch.sh"
grep -Fq 'sound="$(normalize_bool "$sound")"' "$repo_root/tools/quake_crash_watch.sh"
grep -q 'quantum_render_update_interval \$render_update_interval' "$repo_root/tools/quake_crash_watch.sh"
grep -q 'quantum_render_update_interval", "1"' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'render_update_interval="${QGE_RENDER_UPDATE_INTERVAL:-1}"' "$repo_root/tools/quake_graphics_stream.sh"
grep -q 'render_update_interval="${QGE_RENDER_UPDATE_INTERVAL:-1}"' "$repo_root/tools/quake_crash_watch.sh"
grep -q 'The default interval is `1`' "$repo_root/docs/qge_agent_stream.md"
grep -q 'timed_out=1' "$repo_root/tools/quake_crash_watch.sh"
grep -q 'exit_status=\$?' "$repo_root/tools/quake_crash_watch.sh"
grep -q 'QGE_CRASH_WATCH_TIMEOUT status=\$exit_status' "$repo_root/tools/quake_crash_watch.sh"
grep -q 'QGE_CRASH_WATCH_DONE status=\$exit_status' "$repo_root/tools/quake_crash_watch.sh"
grep -Fq 'qconsole_file="$basedir/qconsole.log"' "$repo_root/tools/quake_crash_watch.sh"
grep -Fq 'qconsole_root_file="$repo_root/qconsole.log"' "$repo_root/tools/quake_crash_watch.sh"
grep -Fq 'cp "$qconsole_file" "$outdir/qconsole.log"' "$repo_root/tools/quake_crash_watch.sh"
grep -Fq 'cp "$qconsole_root_file" "$outdir/qconsole.root.log"' "$repo_root/tools/quake_crash_watch.sh"
grep -Fq 'rm -f "$qconsole_file"' "$repo_root/tools/quake_crash_watch.sh"
grep -Fq 'rm -f "$qconsole_root_file"' "$repo_root/tools/quake_crash_watch.sh"
grep -q 'input/noesis_actions.txt' "$repo_root/docs/qge_agent_stream.md"
grep -q 'diagnostics/agent_stream/latest_stream.txt' "$repo_root/docs/qge_agent_stream.md"
grep -q 'QGE_STREAM_TIMEOUT_SECONDS' "$repo_root/docs/qge_agent_stream.md"
grep -q 'child process exit status' "$repo_root/docs/qge_agent_stream.md"
grep -q 'process exit status in its final' "$repo_root/docs/qge_agent_stream.md"
grep -q 'QGE_NOESIS_MAX_WAIT' "$repo_root/tools/noesis_quake_player.sh"
grep -q 'wait_clamped requested=' "$repo_root/tools/noesis_quake_player.sh"
grep -q 'qge_noesis_summary.py' "$repo_root/tools/quake_graphics_stream.sh"
grep -q 'qge_noesis_summary.json' "$repo_root/tools/quake_graphics_stream.sh"
grep -q 'qge_noesis_icc_evidence.json' "$repo_root/tools/quake_graphics_stream.sh"
grep -q 'agent_stream_noesis_status' "$repo_root/tools/quake_graphics_stream.sh"
grep -q 'agent_noesis_summary_file' "$repo_root/tools/quake_graphics_stream.sh"
grep -q 'agent_noesis_icc_evidence_file' "$repo_root/tools/quake_graphics_stream.sh"
grep -q 'agent_noesis_gameplay_file' "$repo_root/tools/quake_graphics_stream.sh"
grep -q '"noesis": {' "$repo_root/tools/quake_graphics_stream.sh"
grep -q 'gameplay_outcomes_file' "$repo_root/tools/quake_graphics_stream.sh"
grep -q 'qge_noesis_summary.py' "$repo_root/docs/qge_agent_stream.md"
grep -q 'qge_noesis_summary.json' "$repo_root/docs/qge_agent_stream.md"
grep -q 'agent_stream_noesis_status' "$repo_root/docs/qge_agent_stream.md"
grep -Fq 'plan="${QGE_NOESIS_PLAN:-adaptive}"' "$repo_root/tools/noesis_quake_player.sh"
grep -Fq 'plan="${QGE_NOESIS_PLAN:-adaptive}"' "$repo_root/tools/noesis_quake_policy.sh"
grep -Fq 'start-hub-route)' "$repo_root/tools/noesis_quake_player.sh"
grep -Fq 'emit_start_hub_route()' "$repo_root/tools/noesis_quake_policy.sh"
grep -Fq 'noesis_plan="${QGE_NOESIS_PLAN:-adaptive}"' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq 'noesis_plan="${QGE_NOESIS_PLAN:-adaptive}"' "$repo_root/tools/quake_crash_watch.sh"
grep -Fq 'scripted="${QGE_NOESIS_SCRIPTED:-0}"' "$repo_root/tools/noesis_quake_player.sh"
grep -Fq 'noesis_scripted="${QGE_NOESIS_SCRIPTED:-0}"' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq 'noesis_scripted="${QGE_NOESIS_SCRIPTED:-0}"' "$repo_root/tools/quake_crash_watch.sh"
grep -Fq 'noesis_autonomous="${QGE_NOESIS_AUTONOMOUS:-}"' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq 'noesis_autonomous="${QGE_NOESIS_AUTONOMOUS:-}"' "$repo_root/tools/quake_crash_watch.sh"
grep -Fq 'noesis_require_combat="${QGE_NOESIS_REQUIRE_COMBAT:-}"' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq 'QGE_NOESIS_SCRIPTED="$noesis_scripted"' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq 'QGE_NOESIS_SCRIPTED="$noesis_scripted"' "$repo_root/tools/quake_crash_watch.sh"
grep -Fq 'QGE_NOESIS_SCRIPTED+x' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq 'qge_noesis_autonomous $noesis_autonomous' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq 'qge_noesis_autonomous $noesis_autonomous' "$repo_root/tools/quake_crash_watch.sh"
grep -q 'noesis_require_combat=$noesis_require_combat' "$repo_root/tools/quake_graphics_stream.sh"
grep -q 'QGE_NOESIS_REQUIRE_COMBAT' "$repo_root/docs/qge_agent_stream.md"
grep -q 'emit_start "autonomous"' "$repo_root/tools/noesis_quake_player.sh"
grep -q 'QGE_NOESIS_SCRIPTED' "$repo_root/docs/qge_agent_stream.md"
grep -Fq 'stream_activate="${QGE_STREAM_ACTIVATE:-0}"' "$repo_root/tools/quake_graphics_stream.sh"
grep -q 'SCR_QGEAutoCaptureSuppressOverlay' "$repo_root/quake/Quake/gl_screen.c"
grep -q 'scr_qge_autocapture_quit_pending' "$repo_root/quake/Quake/gl_screen.c"
grep -q 'key_dest = key_console' "$repo_root/quake/Quake/gl_screen.c"
grep -q 'Host_Quit_f()' "$repo_root/quake/Quake/gl_screen.c"
grep -q 'if (!qge_autocapture_frame)' "$repo_root/quake/Quake/gl_screen.c"
grep -q 'capture is active' "$repo_root/docs/qge_agent_stream.md"
grep -q 'console quit path' "$repo_root/docs/qge_agent_stream.md"
grep -q 'quantum_render_edge_gain", "0"' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'render_edge_gain="${QGE_RENDER_EDGE_GAIN:-0}"' "$repo_root/tools/quake_graphics_stream.sh"
grep -q 'render_edge_gain="${QGE_RENDER_EDGE_GAIN:-0}"' "$repo_root/tools/quake_crash_watch.sh"
grep -q 'render_edge_gain="${QGE_RENDER_EDGE_GAIN:-0}"' "$repo_root/tools/quake_graphics_harness.sh"
grep -q 'world-edge overlay is opt-in' "$repo_root/docs/qge_agent_stream.md"
grep -q 'perspective-correct interpolation' "$repo_root/docs/qge_agent_stream.md"
grep -q '1.0f / a->depth' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'prepared surface texture and' "$repo_root/docs/qge_agent_stream.md"
grep -q 'Failed to create command queue' "$repo_root/qge/qge_metal.mm"
grep -q 'commandQueue != nil' "$repo_root/qge/qge_metal.mm"
grep -q 'only considered available when it can create' "$repo_root/docs/qge_agent_stream.md"
grep -q 'advance-fire' "$repo_root/tools/noesis_quake_player.sh"
grep -q 'wall-slide-right' "$repo_root/tools/noesis_quake_player.sh"
grep -q 'door-bump' "$repo_root/tools/noesis_quake_player.sh"
grep -q 'door-open' "$repo_root/tools/noesis_quake_player.sh"
grep -q 'speed-jump-forward' "$repo_root/tools/noesis_quake_player.sh"
grep -q 'scan-fire-left' "$repo_root/tools/noesis_quake_player.sh"
grep -q 'scan-fire-right' "$repo_root/tools/noesis_quake_player.sh"
grep -q 'attack 1' "$repo_root/tools/noesis_quake_policy.sh"
grep -q 'circle-left' "$repo_root/tools/noesis_quake_policy.sh"
grep -q 'door-open' "$repo_root/tools/noesis_quake_policy.sh"
grep -q 'e1m1-route-push' "$repo_root/tools/noesis_quake_policy.sh"
grep -q 'QGE_NOESIS_PHASE' "$repo_root/tools/noesis_quake_policy.sh"
grep -q 'phase=e1m1_hunt_loop' "$repo_root/tools/noesis_quake_policy.sh"
grep -q 'back 8' "$repo_root/tools/noesis_quake_policy.sh"
grep -q 'speed-jump-forward 6' "$repo_root/tools/noesis_quake_policy.sh"
grep -q 'a keyboard-only back/turn/jump unstick prelude' "$repo_root/docs/qge_agent_stream.md"
grep -q 'QGE_SCENE_SURFACE_BUDGET:-512' "$repo_root/tools/quake_graphics_stream.sh"
grep -q 'quantum_scene_surface_budget", "512"' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'quantum_render_bilinear_samples", "1"' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'quantum_render_detail_mix", "1.0"' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'quantum_render_display_filter", "0"' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_RENDER_BILINEAR_SAMPLES:-1' "$repo_root/tools/quake_graphics_stream.sh"
grep -q 'QGE_RENDER_BILINEAR_SAMPLES:-1' "$repo_root/tools/quake_crash_watch.sh"
grep -q 'QGE_RENDER_DETAIL_MIX:-1.0' "$repo_root/tools/quake_graphics_stream.sh"
grep -q 'QGE_RENDER_DETAIL_MIX:-1.0' "$repo_root/tools/quake_crash_watch.sh"
grep -q 'render_detail_mix="${render_detail_mix:-1.0}"' "$repo_root/tools/quake_graphics_stream.sh"
grep -q 'render_detail_mix="${render_detail_mix:-1.0}"' "$repo_root/tools/quake_crash_watch.sh"
grep -q 'QGE_RENDER_DISPLAY_FILTER:-0' "$repo_root/tools/quake_graphics_stream.sh"
grep -q 'QGE_RENDER_DISPLAY_FILTER:-0' "$repo_root/tools/quake_crash_watch.sh"
grep -q 'QGE_RENDER_DETAIL_MIX' "$repo_root/docs/qge_agent_stream.md"
grep -q 'QGE_RenderUseSpatialNoFloorTone' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_NO_FLOOR_TONE_WHITE_HEADROOM 9.50f' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_SURFACE_TEXTURE_AMBIENT 0.06f' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_SURFACE_LIGHT_AMBIENT 0.10f' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_SURFACE_WORLD_BLUE_BALANCE 0.88f' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_SURFACE_TEXTURE_DETAIL_RESTORE 0.28f' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_SURFACE_TEXTURE_DETAIL_HIGHLIGHT_SCALE 0.35f' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_SurfaceRestoreTextureDetail' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'texture_mean_r' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'out.r += QGE_SURFACE_LUMA_FLOOR - luma' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_SURFACE_FULLBRIGHT_INDEX 224' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_SURFACE_FULLBRIGHT_SCALE 1.35f' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'palette_index >= QGE_SURFACE_FULLBRIGHT_INDEX' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_TONE_HISTOGRAM_WORLD_Y_PERCENT 72' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'hist_pixel_limit = hist_rows \* qge_render_res' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_SPATIAL_DEPTH_EPSILON 0.25f' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'white \*= QGE_NO_FLOOR_TONE_WHITE_HEADROOM' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_SURFACE_TEXTURE_AMBIENT' "$repo_root/docs/qge_agent_stream.md"
grep -q 'QGE_SURFACE_WORLD_BLUE_BALANCE' "$repo_root/docs/qge_agent_stream.md"
grep -q 'QGE_SURFACE_TEXTURE_DETAIL_RESTORE' "$repo_root/docs/qge_agent_stream.md"
grep -q 'QGE_SURFACE_TEXTURE_DETAIL_HIGHLIGHT_SCALE' "$repo_root/docs/qge_agent_stream.md"
grep -q 'QGE_SURFACE_FULLBRIGHT_INDEX' "$repo_root/docs/qge_agent_stream.md"
grep -q 'QGE_TONE_HISTOGRAM_WORLD_Y_PERCENT' "$repo_root/docs/qge_agent_stream.md"
grep -q 'QGE_SPATIAL_DEPTH_EPSILON' "$repo_root/docs/qge_agent_stream.md"
grep -q 'QGE_NO_FLOOR_TONE_WHITE_HEADROOM' "$repo_root/docs/qge_agent_stream.md"
grep -q 'fprintf(stderr, "QGE render frame=' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'fprintf(stderr, "QGE snapshot frame=' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'stderr instead of' "$repo_root/docs/qge_agent_stream.md"
! grep -q 'Con_Printf("QGE render frame=' "$repo_root/quake/Quake/qge_hooks.c"
! grep -q 'Con_Printf("QGE snapshot frame=' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'floor_val = no_floor_tone ? 0.0f' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'uses the existing tone curve without the' "$repo_root/docs/qge_agent_stream.md"
grep -q 'QGE_SurfaceTexturePaletteOpaque' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'if (!ctx->fence)' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'fence/transparent surfaces use palette alpha' "$repo_root/docs/qge_agent_stream.md"
grep -q 'qge_palette_lut\[i\].r = (float)rgba\[0\] \* inv_255;' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'base Quake palette without a global fullbright' "$repo_root/docs/qge_agent_stream.md"
grep -q 'tanf(fov_y' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'r_refdef.fov_x` and `r_refdef.fov_y`' "$repo_root/docs/qge_agent_stream.md"
grep -q 'QGE_SURFACE_NEAR_CLIP_DEPTH 8.0f' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'dist < QGE_SURFACE_NEAR_CLIP_DEPTH' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_SURFACE_NEAR_CLIP_DEPTH' "$repo_root/docs/qge_agent_stream.md"
grep -q 'ctx->warp = surface && (surface->flags & SURF_DRAWTURB)' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'tex_s \*= 2.0f' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'tex_s \*= 1.0f / 64.0f' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'already-scaled undivided water-poly coordinates' "$repo_root/docs/qge_agent_stream.md"
grep -q 'QGE_SPATIAL_WORLD_BACKGROUND_R 0.018f' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_SpatialFillWorldBackground();' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'far-depth ambient world background' "$repo_root/docs/qge_agent_stream.md"
grep -q 'QGE_SPATIAL_SEAM_REPAIR_MIN_NEIGHBORS 3' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_SPATIAL_SEAM_REPAIR_DEPTH_RATIO 0.25f' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_SpatialRepairWorldCoverageGaps();' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'gaprepair' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'one-pixel floor/wall/ceiling coverage gaps' "$repo_root/docs/qge_agent_stream.md"
grep -q 'QGE_MAX_ALIAS_VIEWMODEL_TRIS 384' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'tri_budget = viewmodel ? QGE_MAX_ALIAS_VIEWMODEL_TRIS' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_AliasSkinSample' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_FillAliasTriangleTextured' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'hdr->texels\[skin\]' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'mesh->st\[0\] + 0.5f' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'Alias-model mesh encoding also covers the first-person viewmodel' "$repo_root/docs/qge_agent_stream.md"
grep -q 'alias-model skin texels' "$repo_root/docs/qge_agent_stream.md"
grep -q 'QGE_TEXTURE_BILINEAR_MIN_FOOTPRINT 1.00f' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'ctx->bilinear && tex_footprint >= QGE_TEXTURE_BILINEAR_MIN_FOOTPRINT' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_TEXTURE_PREFILTER_MIN_FOOTPRINT 1.75f' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_TEXTURE_PREFILTER_GRID_FOOTPRINT 3.25f' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_TEXTURE_PREFILTER_MAX_FOOTPRINT 6.0f' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_ProjectedTriangleTextureFootprint' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_SurfaceTexturePrefilterContext' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'texfilter' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'stratified 4x4 footprint grid' "$repo_root/docs/qge_agent_stream.md"
grep -q 'one-texel and minified pixels' "$repo_root/docs/qge_agent_stream.md"
grep -q 'Moderate minification uses the nine-tap path' "$repo_root/docs/qge_agent_stream.md"
grep -q 'QGE_RenderGateMarginalProbabilities' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'state_probabilities\[5\]' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'finite-shot counters remain logged as measurement telemetry' "$repo_root/docs/qge_agent_stream.md"
grep -q 'Latest verified runtime baseline is the current QGE world texture-detail' "$repo_root/docs/qge_state_of_development.md"
grep -q 'diagnostic notify cleanup' "$repo_root/README.md"
grep -q 'diagnostic notify' "$repo_root/docs/qge_state_of_development.md"
grep -q 'world fullbright sampling scale' "$repo_root/README.md"
grep -q '20260521-143859/frame_001.png' "$repo_root/docs/qge_state_of_development.md"
grep -q '20260521-153315/frame_001.png' "$repo_root/docs/qge_state_of_development.md"
grep -q '20260521-155209/frame_001.png' "$repo_root/docs/qge_state_of_development.md"
grep -q '20260521-164816/frame_001.png' "$repo_root/docs/qge_state_of_development.md"
grep -q '20260521-170934/frame_001.png' "$repo_root/docs/qge_state_of_development.md"
grep -q '20260521-173303/frame_001.png' "$repo_root/docs/qge_state_of_development.md"
grep -q '20260521-174755/frame_001.png' "$repo_root/docs/qge_state_of_development.md"
grep -q '20260521-180918/frame_002.png' "$repo_root/docs/qge_state_of_development.md"
grep -q '20260521-183949/frame_001.png' "$repo_root/docs/qge_state_of_development.md"
grep -q '20260521-190448/frame_001.png' "$repo_root/docs/qge_state_of_development.md"
grep -q '0.0452656' "$repo_root/docs/qge_state_of_development.md"
grep -q '0.0349406' "$repo_root/docs/qge_state_of_development.md"
grep -q '0.0343281' "$repo_root/docs/qge_state_of_development.md"
grep -q '0.0341756' "$repo_root/docs/qge_state_of_development.md"
grep -q '0.0340944' "$repo_root/docs/qge_state_of_development.md"
grep -q '0.0349406' "$repo_root/README.md"
grep -q '0.0343281' "$repo_root/README.md"
grep -q 'QGE primary rendering updates every host frame by default' "$repo_root/docs/qge_state_of_development.md"
grep -q 'QGE graphics shimmer on a static camera' "$repo_root/docs/qge_state_of_development.md"
grep -q 'QGE_FrameSnapshotClearVisibleSurfaces' "$repo_root/quake/Quake/qge_hooks.h"
grep -q 'QGE_FrameSnapshotClearVisibleSurfaces();' "$repo_root/quake/Quake/r_world.c"
grep -q 'snapshot->visible_surface_count = 0' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'preventing duplicate world panels' "$repo_root/docs/qge_agent_stream.md"
grep -q 'QGE_SpatialKeepLumaOwnerRGB' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'Same-depth world samples use whole-sample luma ownership' "$repo_root/docs/qge_agent_stream.md"
grep -q 'QGE_MixSpatialDetailIntoRender' "$repo_root/quake/Quake/qge_hooks.c"
grep -Fq 'qge_dwt_encode_spatial(qge_dwt_fb[ch], source' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'Detail-preserving QGE render output' "$repo_root/docs/qge_state_of_development.md"
grep -q 'default `512`' "$repo_root/docs/qge_agent_stream.md"
grep -q 'QGE_NOESIS_MAX_WAIT' "$repo_root/docs/qge_agent_stream.md"
grep -q 'combat-explore' "$repo_root/docs/qge_agent_stream.md"
grep -q 'advance-fire' "$repo_root/docs/qge_agent_stream.md"
grep -q 'wall-slide-right' "$repo_root/docs/qge_agent_stream.md"
grep -q 'door-bump' "$repo_root/docs/qge_agent_stream.md"
grep -q 'door-open' "$repo_root/docs/qge_agent_stream.md"
grep -q 'speed-jump-forward' "$repo_root/docs/qge_agent_stream.md"
grep -q 'scan-fire-left' "$repo_root/docs/qge_agent_stream.md"
grep -q 'noesis_gameplay_quality_score' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'noesis_claim_scope' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'noesis_scripted' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'noesis_autonomous' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'noesis_autonomous_control' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'noesis_unassisted_claim_supported' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'noesis_gameplay_outcome_sample_count' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'noesis_gameplay_total_distance' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'noesis_gameplay_terminal_stall' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'noesis_gameplay_max_stationary_run' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'noesis_gameplay_stationary_fraction' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'noesis_gameplay_movement_efficiency' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'noesis_gameplay_phase_event_count' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'noesis_gameplay_phase_stuck_window_count' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'noesis_projectile_save_demo_boundary_count' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'noesis_projectile_save_demo_trace_id_xor' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'noesis_replay_metadata_mismatches' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'noesis_trace_qge_build_hash' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'noesis_gameplay_attack_visible_frames' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'noesis_gameplay_attack_aligned_frames' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'noesis_gameplay_blind_attack_frames' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'noesis_gameplay_visible_unaligned_attack_frames' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'noesis_gameplay_unproductive_attack_frames' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'noesis_gameplay_nearest_enemy_angle_error_min' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'noesis_gameplay_net_damage_per_attack_press' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'noesis_gameplay_ammo_spent' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'noesis_gameplay_unproductive_ammo_spent' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'noesis_gameplay_ammo_waste_fraction' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'noesis_gameplay_damage_per_ammo_spent' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'combat_opportunity' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'close_enemy_contact_sample_count' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'close enemy-contact samples' "$repo_root/docs/qge_agent_stream.md"
grep -q 'Blind fire by itself does not turn a route-only interval into a' "$repo_root/docs/qge_agent_stream.md"
grep -q 'combat_effectiveness_required' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'terminal_stall_threshold' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'noesis_assist_requested_mode' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'noesis_assist_active_fraction' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'noesis_assist_active_sample_count' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'noesis_assist_target_visible_sample_count' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'noesis_assist_steering_sample_count' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'noesis_assist_view_injected_sample_count' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'noesis_assist_movement_injected_sample_count' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'noesis_assist_attack_injected_sample_count' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'noesis_assist_attack_suppressed_sample_count' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'noesis_assist_pre_assist_aim_error_min' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'noesis_assist_target_locked_sample_count' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'noesis_assist_target_switch_count' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'noesis_assist_switch_fire_suppressed_sample_count' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'noesis_route_action_count' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'noesis_log_phase_count' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'door-open' "$repo_root/tools/qge_noesis_summary.py"
grep -Fq 'noesis_min_log_phases="${QGE_NOESIS_MIN_LOG_PHASES:-0}"' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq 'noesis_min_gameplay_samples="${QGE_NOESIS_MIN_GAMEPLAY_SAMPLES:-2}"' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq 'noesis_min_route_distance="${QGE_NOESIS_MIN_ROUTE_DISTANCE:-64}"' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq 'noesis_min_capture_wait="${QGE_NOESIS_MIN_CAPTURE_WAIT:-280}"' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq '"noesis_min_capture_wait": $noesis_min_capture_wait' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq 'if (( noesis_min_capture_wait > noesis_capture_min )); then' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq 'noesis_assist="${QGE_NOESIS_ASSIST:-2}"' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq 'noesis_assist="$(normalize_nonnegative_int "$noesis_assist" 2)"' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq '"noesis_min_log_phases": $noesis_min_log_phases' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq '"noesis_min_gameplay_samples": $noesis_min_gameplay_samples' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq '"noesis_assist": $noesis_assist' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq 'qge_noesis_assist $noesis_assist' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq -- '--min-log-phases "$noesis_min_log_phases"' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq -- '--min-phase-outcomes "$noesis_min_log_phases"' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq -- '--min-gameplay-samples "$noesis_min_gameplay_samples"' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq 'noesis_args+=(--require-combat)' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq 'if (( frames >= 2 )); then' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq 'noesis_args+=(--min-frame-mae 2.0)' "$repo_root/tools/quake_graphics_stream.sh"
grep -q 'QGE_NOESIS_MIN_LOG_PHASES' "$repo_root/docs/qge_agent_stream.md"
grep -q 'QGE_NOESIS_MIN_GAMEPLAY_SAMPLES' "$repo_root/docs/qge_agent_stream.md"
grep -q 'QGE_NOESIS_MIN_CAPTURE_WAIT' "$repo_root/docs/qge_agent_stream.md"
grep -q 'QGE_NOESIS_ASSIST' "$repo_root/docs/qge_agent_stream.md"
grep -q 'claim scope' "$repo_root/docs/qge_agent_stream.md"
grep -q 'attack-aligned frame counts' "$repo_root/docs/qge_agent_stream.md"
grep -q 'closes farther along the left bridge side' "$repo_root/docs/qge_agent_stream.md"
grep -q 'Scripted fixture runs remain marked `server_assisted`' "$repo_root/docs/qge_agent_stream.md"
grep -q 'kites visible close' "$repo_root/docs/qge_agent_stream.md"
grep -q 'Hidden distant targets do not override' "$repo_root/docs/qge_agent_stream.md"
grep -q 'QGE_NoesisAssistClientThink' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_GameplayEnemyAimPoint' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_GameplayAimErrorDegrees(player, candidate_aim)' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'pre_assist_aim_error_deg' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'view_injected' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'movement_injected' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'attack_injected' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'target_locked' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'switch_fire_suppressed' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_NOESIS_TARGET_LOCK_FRAMES' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_NOESIS_VIEW_HOLD_DEG' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'qge_noesis_autonomous' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_NOESIS_AUTONOMOUS_CHASE_DISTANCE 1152.0f' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_NOESIS_WALL_TRAP_CLEAR 40.0f' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_NOESIS_WALL_SLIDE_CLEAR 56.0f' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_NOESIS_WALL_FOLLOW_FRAMES 24' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_NOESIS_EXPLORE_TURN_DEG 24.0f' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_NOESIS_EXPLORE_FLOOR_PROBE_DISTANCE 64.0f' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_NOESIS_EXPLORE_FLOOR_DROP 96.0f' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_NoesisAssistPathHasFloor' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'SV_PointContents(contents_point)' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_NoesisAssistAutonomousExplore' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_NoesisAssistAutonomousExplore(player, move' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'local clearance exploration' "$repo_root/docs/qge_agent_stream.md"
grep -q 'QGE_NOESIS_EXPLORE_FLOOR_PROBE_DISTANCE' "$repo_root/docs/qge_agent_stream.md"
grep -q 'QGE_NOESIS_HIDDEN_CHASE_VISIBILITY_TIMEOUT_FRAMES 80' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_NOESIS_HIDDEN_CHASE_COOLDOWN_FRAMES 120' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_NOESIS_HIDDEN_WALL_STALL_DISTANCE 1152.0f' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_NOESIS_HIDDEN_WALL_STALL_FRAMES 30' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_NOESIS_VISIBLE_BREAK_HIDDEN_LOCK_DISTANCE 512.0f' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'best_visible_distance >' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_NOESIS_VISIBLE_BREAK_HIDDEN_LOCK_DISTANCE' "$repo_root/docs/qge_agent_stream.md"
grep -q 'QGE_NoesisAssistWallFollowSide' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_NoesisAssistHiddenCoolingDown' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_NoesisAssistHiddenWallStalled' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'relative_forward = -220.0f' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'relative_forward = visible ? 120.0f : 0.0f' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_NOESIS_WALL_TRAP_CLEAR' "$repo_root/docs/qge_agent_stream.md"
grep -q 'QGE_NOESIS_WALL_SLIDE_CLEAR' "$repo_root/docs/qge_agent_stream.md"
grep -q 'QGE_NOESIS_WALL_FOLLOW_FRAMES' "$repo_root/docs/qge_agent_stream.md"
grep -q 'QGE_NOESIS_HIDDEN_CHASE_VISIBILITY_TIMEOUT_FRAMES' "$repo_root/docs/qge_agent_stream.md"
grep -q 'QGE_NOESIS_HIDDEN_WALL_STALL_FRAMES' "$repo_root/docs/qge_agent_stream.md"
grep -q 'hidden_chase_timeout' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'hidden_chase_timeout_count' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'hidden_wall_timeout_count' "$repo_root/tools/qge_noesis_summary.py"
grep -q 'pre_aim_error > QGE_NOESIS_VIEW_HOLD_DEG' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_NoesisAssistSetRelativeMove(move, movement_yaw, aim\[YAW\]' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'move->forwardmove = DotProduct(wish, basis_forward)' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'remove forward pressure for hidden targets' "$repo_root/docs/qge_agent_stream.md"
grep -q 'enemy = QGE_NoesisAssistFindEnemy(player, chase_mode ? false : true' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_NOESIS_AIM_ALIGNED_DEG' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'qge_gameplay_attack_aligned_total' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'distance < 192.0f' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'engage_target = visible' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_NOESIS_HIDDEN_CHASE_DISTANCE 768.0f' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'QGE_NoesisAssistHiddenChaseDistance' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'strcmp(qge_noesis_current_phase, "e1m1_bridge_route")' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'q_strlcpy(qge_noesis_current_phase, phase' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'visible-only for combat takeover' "$repo_root/docs/qge_agent_stream.md"
grep -Fq 'relative_side = wall_follow_side * 320.0f;' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'player->v.button0 = 0.0f' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'Cmd_AddCommand("qge_noesis_phase", QGE_NoesisPhase_f)' "$repo_root/quake/Quake/qge_hooks.c"
grep -q '\\"kind\\":\\"noesis_phase\\"' "$repo_root/quake/Quake/qge_hooks.c"
grep -q '\\"assist\\"' "$repo_root/quake/Quake/qge_hooks.c"
grep -q 'gameplay_outcomes.ndjson' "$repo_root/docs/qge_agent_stream.md"
grep -q 'weapon-cycle-smoke' "$repo_root/docs/qge_agent_stream.md"
grep -Fq 'noesis_max_wait="${QGE_NOESIS_MAX_WAIT:-600}"' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq '"noesis_max_wait": $noesis_max_wait' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq 'fire_min_start_wait="${QGE_STREAM_FIRE_MIN_START_WAIT:-48}"' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq 'fire_min_frames="${QGE_STREAM_FIRE_MIN_FRAMES:-8}"' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq '"fire_min_start_wait": $fire_min_start_wait' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq '"fire_min_frames": $fire_min_frames' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq '"engine_capture_wait": $manifest_engine_capture_wait' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq 'QGE_NOESIS_CAPTURE_HOLD' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq 'QGE_NOESIS_ASSIST' "$repo_root/tools/quake_graphics_stream.sh"
grep -q 'QGE_STREAM_FIRE_MIN_START_WAIT' "$repo_root/docs/qge_agent_stream.md"
grep -q 'QGE_NOESIS_CAPTURE_HOLD' "$repo_root/docs/qge_agent_stream.md"
grep -q 'projectile authority warmup' "$repo_root/docs/qge_agent_stream.md"
grep -q 'active_projectiles_max' "$repo_root/docs/qge_agent_stream.md"
grep -Fq 'QGE_NOESIS_MAX_WAIT="$noesis_max_wait"' "$repo_root/tools/quake_graphics_stream.sh"
grep -Fq 'QGE_NOESIS_MAX_WAIT="$noesis_max_wait"' "$repo_root/tools/quake_crash_watch.sh"
grep -Fq 'rm -f "$runtime_log_file"' "$repo_root/tools/quake_graphics_stream.sh"
grep -q 'removes the root `qconsole.log` copy' "$repo_root/docs/qge_agent_stream.md"
grep -q 'archives it and then removes' "$repo_root/docs/qge_agent_stream.md"

python3 "$repo_root/tools/qge_image_metrics.py" --help > "$tmpdir/image_metrics_help.txt"
grep -q -- '--check-deps' "$tmpdir/image_metrics_help.txt"

actions_file="$tmpdir/actions.txt"
commands_file="$tmpdir/commands.cfg"
stdout_file="$tmpdir/stdout.cfg"

QGE_NOESIS_DIR="$repo_root" \
QGE_NOESIS_PLAN=map-scout \
QGE_STREAM_MAP=e1m1 \
QGE_NOESIS_CMD="$repo_root/tools/noesis_quake_policy.sh" \
QGE_NOESIS_START_WAIT=0 \
QGE_NOESIS_ACTION_TRACE_FILE="$actions_file" \
QGE_NOESIS_COMMAND_TRACE_FILE="$commands_file" \
  "$repo_root/tools/noesis_quake_player.sh" > "$stdout_file"

cmp -s "$stdout_file" "$commands_file"

grep -q '^cmd echo QGE_NOESIS_POLICY .*map=e1m1 plan=map-scout' "$actions_file"
grep -q '^forward 8$' "$actions_file"
grep -q '^weapon 7$' "$actions_file"
grep -q '^attack 8$' "$actions_file"
grep -q '^cmd echo QGE_NOESIS_POLICY done$' "$actions_file"

grep -q '^echo QGE_NOESIS_PLAYER start .*source=cmd .*start_wait=0' "$commands_file"
grep -q '^echo QGE_NOESIS_POLICY .*map=e1m1 plan=map-scout' "$commands_file"
grep -q '^+forward$' "$commands_file"
grep -q '^-forward$' "$commands_file"
grep -q '^impulse 7$' "$commands_file"
grep -q '^+attack$' "$commands_file"
grep -q '^-attack$' "$commands_file"
grep -q '^echo QGE_NOESIS_PLAYER done$' "$commands_file"

action_count="$(wc -l < "$actions_file" | tr -d ' ')"
command_count="$(wc -l < "$commands_file" | tr -d ' ')"
if [[ "$action_count" != "13" ]]; then
  echo "expected 13 Noesis action lines, got $action_count" >&2
  exit 1
fi
if (( command_count < 50 )); then
  echo "expected translated Quake command trace, got only $command_count lines" >&2
  exit 1
fi

recovery_actions="$tmpdir/recovery-actions.txt"
recovery_commands="$tmpdir/recovery-commands.cfg"
recovery_stdout="$tmpdir/recovery-stdout.cfg"

QGE_NOESIS_DIR="$repo_root" \
QGE_NOESIS_PLAN=combat-explore \
QGE_STREAM_MAP=start \
QGE_NOESIS_CMD="$repo_root/tools/noesis_quake_policy.sh" \
QGE_NOESIS_START_WAIT=0 \
QGE_NOESIS_ACTION_TRACE_FILE="$recovery_actions" \
QGE_NOESIS_COMMAND_TRACE_FILE="$recovery_commands" \
  "$repo_root/tools/noesis_quake_player.sh" > "$recovery_stdout"

cmp -s "$recovery_stdout" "$recovery_commands"
grep -q '^cmd echo QGE_NOESIS_PHASE phase=stuck_recovery$' "$recovery_actions"
grep -q '^back 5$' "$recovery_actions"
grep -q '^wall-slide-left 6$' "$recovery_actions"
grep -q '^turn-right 8$' "$recovery_actions"
grep -q '^jump-forward 5$' "$recovery_actions"
grep -q '^cmd echo QGE_NOESIS_PHASE phase=second_push$' "$recovery_actions"
grep -q '^+back$' "$recovery_commands"
grep -q '^-back$' "$recovery_commands"
grep -q '^+moveleft$' "$recovery_commands"
grep -q '^-moveleft$' "$recovery_commands"
grep -q '^+jump$' "$recovery_commands"

builtin_recovery_actions="$tmpdir/builtin-recovery-actions.txt"
builtin_recovery_commands="$tmpdir/builtin-recovery-commands.cfg"
builtin_recovery_stdout="$tmpdir/builtin-recovery-stdout.cfg"

QGE_NOESIS_DIR="$repo_root" \
QGE_NOESIS_PLAN=combat-explore \
QGE_STREAM_MAP=start \
QGE_NOESIS_START_WAIT=0 \
QGE_NOESIS_SCRIPTED=1 \
QGE_NOESIS_ACTION_TRACE_FILE="$builtin_recovery_actions" \
QGE_NOESIS_COMMAND_TRACE_FILE="$builtin_recovery_commands" \
  "$repo_root/tools/noesis_quake_player.sh" > "$builtin_recovery_stdout"

cmp -s "$builtin_recovery_stdout" "$builtin_recovery_commands"
grep -q '^back 5$' "$builtin_recovery_actions"
grep -q '^wall-slide-left 6$' "$builtin_recovery_actions"
grep -q '^turn-right 8$' "$builtin_recovery_actions"
grep -q '^jump-forward 5$' "$builtin_recovery_actions"
grep -q '^run-forward 10$' "$builtin_recovery_actions"
grep -q '^+back$' "$builtin_recovery_commands"
grep -q '^+moveleft$' "$builtin_recovery_commands"
grep -q '^+jump$' "$builtin_recovery_commands"

autonomous_actions="$tmpdir/autonomous-actions.txt"
autonomous_commands="$tmpdir/autonomous-commands.cfg"
autonomous_stdout="$tmpdir/autonomous-stdout.cfg"

QGE_NOESIS_DIR="$repo_root" \
QGE_NOESIS_SCRIPTED=0 \
QGE_NOESIS_START_WAIT=0 \
QGE_NOESIS_ACTION_TRACE_FILE="$autonomous_actions" \
QGE_NOESIS_COMMAND_TRACE_FILE="$autonomous_commands" \
  "$repo_root/tools/noesis_quake_player.sh" > "$autonomous_stdout"

cmp -s "$autonomous_stdout" "$autonomous_commands"
[[ ! -s "$autonomous_actions" ]]
grep -q '^echo QGE_NOESIS_PLAYER start .*source=autonomous' "$autonomous_commands"
grep -q '^echo QGE_NOESIS_PLAYER autonomous scripts=disabled control=engine_assist$' "$autonomous_commands"
if grep -Eq '^\+(forward|back|left|right|moveleft|moveright|attack|jump)|^impulse |^give ' "$autonomous_commands"; then
  echo "default Noesis player emitted scripted movement in autonomous mode" >&2
  exit 1
fi

adaptive_actions="$tmpdir/adaptive-actions.txt"
adaptive_commands="$tmpdir/adaptive-commands.cfg"
adaptive_stdout="$tmpdir/adaptive-stdout.cfg"

QGE_NOESIS_DIR="$repo_root" \
QGE_NOESIS_PLAN=adaptive \
QGE_STREAM_MAP=e1m1 \
QGE_NOESIS_CMD="$repo_root/tools/noesis_quake_policy.sh" \
QGE_NOESIS_START_WAIT=0 \
QGE_NOESIS_ACTION_TRACE_FILE="$adaptive_actions" \
QGE_NOESIS_COMMAND_TRACE_FILE="$adaptive_commands" \
  "$repo_root/tools/noesis_quake_player.sh" > "$adaptive_stdout"

cmp -s "$adaptive_stdout" "$adaptive_commands"

grep -q '^cmd echo QGE_NOESIS_POLICY .*map=e1m1 plan=adaptive' "$adaptive_actions"
grep -q '^center-view$' "$adaptive_actions"
grep -q '^cmd echo QGE_NOESIS_PHASE phase=e1m1_entry_clear$' "$adaptive_actions"
grep -q '^cmd echo QGE_NOESIS_PHASE phase=e1m1_bridge_route$' "$adaptive_actions"
grep -q '^cmd echo QGE_NOESIS_PHASE phase=e1m1_door_slide$' "$adaptive_actions"
grep -q '^cmd echo QGE_NOESIS_PHASE phase=e1m1_exit_route$' "$adaptive_actions"
grep -q '^look-up 2$' "$adaptive_actions"
grep -q '^turn-left 5$' "$adaptive_actions"
grep -q '^turn-right 10$' "$adaptive_actions"
grep -q '^attack 1$' "$adaptive_actions"
grep -q '^run-forward 12$' "$adaptive_actions"
grep -q '^wall-slide-right 12$' "$adaptive_actions"
grep -q '^circle-left 6$' "$adaptive_actions"
grep -q '^turn-left 10$' "$adaptive_actions"
grep -q '^run-forward 14$' "$adaptive_actions"
grep -q '^wall-slide-left 10$' "$adaptive_actions"
grep -q '^scan-fire-left 12$' "$adaptive_actions"
grep -q '^attack 2$' "$adaptive_actions"
grep -q '^door-open 8$' "$adaptive_actions"
grep -q '^door-bump 6$' "$adaptive_actions"
grep -q '^scan-fire-left 6$' "$adaptive_actions"
grep -q '^scan-fire-right 6$' "$adaptive_actions"
grep -q '^speed-jump-forward 4$' "$adaptive_actions"
grep -q '^clear-input 2$' "$adaptive_actions"
grep -q '^cmd echo QGE_NOESIS_POLICY done$' "$adaptive_actions"
adaptive_speed_jump_count="$(grep -c '^speed-jump-forward 4$' "$adaptive_actions" | tr -d ' ')"
if (( adaptive_speed_jump_count < 1 )); then
  echo "expected E1M1 adaptive route to include post-door speed jump recovery" >&2
  exit 1
fi
adaptive_attack_tap_count="$(grep -c '^attack 1$' "$adaptive_actions" | tr -d ' ')"
if (( adaptive_attack_tap_count < 3 )); then
  echo "expected E1M1 adaptive route to keep disciplined attack taps" >&2
  exit 1
fi
if grep -Eq '^(advance-fire|circle-fire|strafe-fire)' "$adaptive_actions"; then
  echo "E1M1 adaptive route kept long default fire holds" >&2
  exit 1
fi

grep -q '^echo QGE_NOESIS_PHASE phase=e1m1_entry_clear$' "$adaptive_commands"
grep -q '^qge_noesis_phase phase=e1m1_entry_clear$' "$adaptive_commands"
grep -q '^qge_noesis_phase phase=e1m1_bridge_route$' "$adaptive_commands"
grep -q '^qge_noesis_phase phase=e1m1_door_slide$' "$adaptive_commands"
grep -q '^qge_noesis_phase phase=e1m1_exit_route$' "$adaptive_commands"
grep -q '^centerview$' "$adaptive_commands"
grep -q '^+forward$' "$adaptive_commands"
grep -q '^+attack$' "$adaptive_commands"
grep -q '^+lookup$' "$adaptive_commands"
grep -q '^+left$' "$adaptive_commands"
grep -q '^+right$' "$adaptive_commands"
grep -q '^+speed$' "$adaptive_commands"
grep -q '^+moveleft$' "$adaptive_commands"
grep -q '^+moveright$' "$adaptive_commands"
grep -q '^+jump$' "$adaptive_commands"
grep -q '^+use$' "$adaptive_commands"
grep -q '^-speed$' "$adaptive_commands"
grep -q '^-use$' "$adaptive_commands"
grep -q '^-lookup$' "$adaptive_commands"
grep -q '^-attack$' "$adaptive_commands"
grep -q '^-forward$' "$adaptive_commands"
grep -q '^echo QGE_NOESIS_PLAYER done$' "$adaptive_commands"

adaptive_command_count="$(wc -l < "$adaptive_commands" | tr -d ' ')"
if (( adaptive_command_count < 150 )); then
  echo "expected rich adaptive Quake command trace, got only $adaptive_command_count lines" >&2
  exit 1
fi

builtin_route_actions="$tmpdir/builtin-route-actions.txt"
builtin_route_commands="$tmpdir/builtin-route-commands.cfg"
builtin_route_stdout="$tmpdir/builtin-route-stdout.cfg"

QGE_NOESIS_DIR="$repo_root" \
QGE_NOESIS_PLAN=e1m1-route-push \
QGE_STREAM_MAP=e1m1 \
QGE_NOESIS_START_WAIT=0 \
QGE_NOESIS_SCRIPTED=1 \
QGE_NOESIS_ACTION_TRACE_FILE="$builtin_route_actions" \
QGE_NOESIS_COMMAND_TRACE_FILE="$builtin_route_commands" \
  "$repo_root/tools/noesis_quake_player.sh" > "$builtin_route_stdout"

cmp -s "$builtin_route_stdout" "$builtin_route_commands"
grep -q '^door-open 8$' "$builtin_route_actions"
grep -q '^door-bump 6$' "$builtin_route_actions"
grep -q '^turn-left 10$' "$builtin_route_actions"
grep -q '^run-forward 14$' "$builtin_route_actions"
grep -q '^wall-slide-left 10$' "$builtin_route_actions"
grep -q '^scan-fire-left 12$' "$builtin_route_actions"
grep -q '^attack 2$' "$builtin_route_actions"
grep -q '^scan-fire-left 6$' "$builtin_route_actions"
grep -q '^scan-fire-right 6$' "$builtin_route_actions"
grep -q '^speed-jump-forward 4$' "$builtin_route_actions"
grep -q '^attack 1$' "$builtin_route_actions"
if grep -q '^jump-forward 3$' "$builtin_route_actions"; then
  echo "built-in E1M1 route kept weak post-door jump-forward recovery" >&2
  exit 1
fi
if grep -Eq '^(advance-fire|circle-fire|strafe-fire)' "$builtin_route_actions"; then
  echo "built-in E1M1 route kept long default fire holds" >&2
  exit 1
fi
grep -q '^+use$' "$builtin_route_commands"
grep -q '^-use$' "$builtin_route_commands"
grep -q '^+forward$' "$builtin_route_commands"
grep -q '^echo QGE_NOESIS_PLAYER done$' "$builtin_route_commands"

combo_actions="$tmpdir/combo-actions.txt"
combo_trace="$tmpdir/combo-trace.txt"
combo_commands="$tmpdir/combo-commands.cfg"
combo_stdout="$tmpdir/combo-stdout.cfg"
cat > "$combo_actions" <<'EOF'
advance-fire 2
wall-slide-left 3
wall-slide-right 2
speed-jump-forward 2
door-open 2
door-bump 3
circle-fire-right 3
scan-fire-left 2
scan-fire-right 2
jump-forward 2
use 1
look-up 1
swim-up 1
center-view
weapon-next
weapon-prev
reload 1
clear-input 1
EOF

QGE_NOESIS_DIR="$repo_root" \
QGE_NOESIS_ACTIONS_FILE="$combo_actions" \
QGE_NOESIS_START_WAIT=0 \
QGE_NOESIS_MAX_WAIT=4 \
QGE_NOESIS_ACTION_TRACE_FILE="$combo_trace" \
QGE_NOESIS_COMMAND_TRACE_FILE="$combo_commands" \
  "$repo_root/tools/noesis_quake_player.sh" > "$combo_stdout"

cmp -s "$combo_stdout" "$combo_commands"
grep -q '^advance-fire 2$' "$combo_trace"
grep -q '^wall-slide-left 3$' "$combo_trace"
grep -q '^wall-slide-right 2$' "$combo_trace"
grep -q '^speed-jump-forward 2$' "$combo_trace"
grep -q '^door-open 2$' "$combo_trace"
grep -q '^door-bump 3$' "$combo_trace"
grep -q '^circle-fire-right 3$' "$combo_trace"
grep -q '^scan-fire-left 2$' "$combo_trace"
grep -q '^scan-fire-right 2$' "$combo_trace"
grep -q '^+forward$' "$combo_commands"
grep -q '^+attack$' "$combo_commands"
grep -q '^+speed$' "$combo_commands"
grep -q '^+moveleft$' "$combo_commands"
grep -q '^+moveright$' "$combo_commands"
grep -q '^+left$' "$combo_commands"
grep -q '^+right$' "$combo_commands"
grep -q '^+jump$' "$combo_commands"
grep -q '^+use$' "$combo_commands"
grep -q '^+lookup$' "$combo_commands"
grep -q '^+moveup$' "$combo_commands"
grep -q '^centerview$' "$combo_commands"
grep -q '^impulse 10$' "$combo_commands"
grep -q '^impulse 12$' "$combo_commands"
grep -q '^echo QGE_NOESIS_PLAYER skipped_unknown_action=reload$' "$combo_commands"
grep -q '^-moveup$' "$combo_commands"
grep -q '^-lookup$' "$combo_commands"
grep -q '^-use$' "$combo_commands"
grep -q '^-right$' "$combo_commands"
grep -q '^-left$' "$combo_commands"
grep -q '^-jump$' "$combo_commands"
grep -q '^-speed$' "$combo_commands"
grep -q '^-attack$' "$combo_commands"

override_actions="$tmpdir/override-actions.txt"
override_commands="$tmpdir/override-commands.cfg"
override_stdout="$tmpdir/override-stdout.cfg"
provider_file="$tmpdir/provider.sh"
actions_input="$tmpdir/input-actions.txt"

printf '%s\n' 'attack 3' > "$actions_input"
cat > "$provider_file" <<'EOF'
#!/usr/bin/env bash
printf '%s\n' 'forward 1'
EOF
chmod +x "$provider_file"

QGE_NOESIS_DIR="$repo_root" \
QGE_NOESIS_ACTIONS_FILE="$actions_input" \
QGE_NOESIS_CMD="$provider_file" \
QGE_NOESIS_START_WAIT=0 \
QGE_NOESIS_ACTION_TRACE_FILE="$override_actions" \
QGE_NOESIS_COMMAND_TRACE_FILE="$override_commands" \
  "$repo_root/tools/noesis_quake_player.sh" > "$override_stdout"

cmp -s "$override_stdout" "$override_commands"
grep -q '^forward 1$' "$override_actions"
grep -q '^+forward$' "$override_commands"
if grep -q '^+attack$' "$override_commands"; then
  echo "QGE_NOESIS_ACTIONS_FILE unexpectedly overrode QGE_NOESIS_CMD" >&2
  exit 1
fi

clamp_actions="$tmpdir/clamp-actions.txt"
clamp_trace="$tmpdir/clamp-trace.txt"
clamp_commands="$tmpdir/clamp-commands.cfg"
clamp_stdout="$tmpdir/clamp-stdout.cfg"
printf '%s\n' 'wait 0008' > "$clamp_actions"

QGE_NOESIS_DIR="$repo_root" \
QGE_NOESIS_ACTIONS_FILE="$clamp_actions" \
QGE_NOESIS_START_WAIT=0 \
QGE_NOESIS_MAX_WAIT=3 \
QGE_NOESIS_ACTION_TRACE_FILE="$clamp_trace" \
QGE_NOESIS_COMMAND_TRACE_FILE="$clamp_commands" \
  "$repo_root/tools/noesis_quake_player.sh" > "$clamp_stdout"

cmp -s "$clamp_stdout" "$clamp_commands"
grep -q '^wait 0008$' "$clamp_trace"
grep -q '^echo QGE_NOESIS_PLAYER wait_clamped requested=8 max=3$' "$clamp_commands"
clamped_wait_count="$(grep -c '^wait$' "$clamp_commands" | tr -d ' ')"
if [[ "$clamped_wait_count" != "3" ]]; then
  echo "expected clamped wait count 3, got $clamped_wait_count" >&2
  exit 1
fi

grep -Fq 'void QGE_2DBeginFrame(void);' "$repo_root/quake/Quake/qge_hooks.h"
grep -Fq 'void QGE_2DSubmitPic(const qpic_t *pic);' "$repo_root/quake/Quake/qge_hooks.h"
grep -Fq 'QGE_2DBeginFrame ();' "$repo_root/quake/Quake/gl_screen.c"
grep -Fq 'QGE_2DSetLayer (QGE_2D_LAYER_CONSOLE);' "$repo_root/quake/Quake/gl_screen.c"
grep -Fq 'QGE_2DEndFrame ();' "$repo_root/quake/Quake/gl_screen.c"
grep -Fq 'QGE_2DSubmitCharacter(*str);' "$repo_root/quake/Quake/gl_draw.c"
grep -Fq 'QGE_2DSubmitPic(pic);' "$repo_root/quake/Quake/gl_draw.c"
grep -Fq 'QGE_2DSubmitFill();' "$repo_root/quake/Quake/gl_draw.c"
grep -Fq 'strlcpy(probe.label, "render_2d_overlay", sizeof(probe.label));' "$repo_root/quake/Quake/qge_hooks.c"
grep -Fq 'own_hud=%d own_console=%d' "$repo_root/quake/Quake/qge_hooks.c"
grep -Fq 'QGE_MEASURE_PROJECTILE_WRITEBACK' "$repo_root/qge/qge_quantum_runtime.h"
grep -Fq 'QGE_MEASURE_PROJECTILE_BRANCH' "$repo_root/qge/qge_quantum_runtime.h"
grep -Fq 'QGE_MEASURE_PROJECTILE_COLLISION_ORACLE' "$repo_root/qge/qge_quantum_runtime.h"
grep -Fq 'QGE_OBSERVE_SAVE_OR_DEMO' "$repo_root/quake/Quake/qge_hooks.c"
grep -Fq 'save_demo_boundary_count' "$repo_root/tools/qge_trace_summary.py"
grep -Fq 'Projectile branch, writeback, and collision-oracle selections also emit' "$repo_root/docs/qge_agent_stream.md"

echo "Noesis input contract: PASSED"
