# GNU Makefile for compiling Mac OS X version of QuakeSpasm.
# Usage: "make -f Makefile.darwin"
# To cross-compile on Linux hosts, see the build_cross_osx*.sh scripts.
# "make DEBUG=1" to build a debug client.
# "make SDL_FRAMEWORK_PATH=/path/to/Frameworks" to specify the directory
#    containing SDL.framework and override the locally included versions.
# "make DO_USERDIRS=1" to enable user directories support

# Enable/Disable user directories support
DO_USERDIRS=0

### Enable/Disable SDL2
USE_SDL2=0

### Enable/Disable codecs for streaming music support
USE_CODEC_WAVE=1
USE_CODEC_FLAC=1
USE_CODEC_MP3=1
USE_CODEC_VORBIS=1
USE_CODEC_OPUS=1
# either xmp or mikmod (or modplug)
USE_CODEC_MIKMOD=0
USE_CODEC_XMP=1
USE_CODEC_MODPLUG=0
USE_CODEC_UMX=1

# which library to use for mp3 decoding: mad or mpg123
MP3LIB=mad
# which library to use for ogg decoding: vorbis or tremor
VORBISLIB=vorbis

# ---------------------------
# Helper functions
# ---------------------------

check_gcc = $(shell if echo | $(CC) $(1) -Werror -S -o /dev/null -xc - > /dev/null 2>&1; then echo "$(1)"; else echo "$(2)"; fi;)

# ---------------------------

MACH_TYPE= $(shell sh detect.sh arch)

DEBUG ?= 0

# ---------------------------
# build variables
# ---------------------------

CC ?= gcc
LINKER = $(CC)
LIPO ?= lipo

STRIP ?= strip -S

CPUFLAGS=
LDFLAGS?=
DFLAGS ?=
CFLAGS ?= -Wall -MMD
# @rpath can be used when targeting 10.5+
USE_RPATH=0
# require 10.5 for 64 bit builds
ifeq ($(MACH_TYPE),ppc64)
CFLAGS  +=-mmacosx-version-min=10.5
LDFLAGS +=-mmacosx-version-min=10.5
USE_RPATH=1
endif
ifeq ($(USE_SDL2),1)
# sdl2 needs targetting 10.5+
# as of v2.0.5, sdl2 targets 10.6+
ifeq ($(MACH_TYPE),x86)
CFLAGS  +=-mmacosx-version-min=10.6
LDFLAGS +=-mmacosx-version-min=10.6
USE_RPATH=1
endif
endif
ifeq ($(MACH_TYPE),x86_64)
# require 10.6 for amd64 builds, not 10.5 (SDL's requirement.)
# bundle1.o is needed for dyld_stub_binding_helper
CFLAGS  +=-mmacosx-version-min=10.6
LDFLAGS +=-mmacosx-version-min=10.6 -Wl,-lbundle1.o
USE_RPATH=1
endif
ifeq ($(MACH_TYPE),arm64)
CFLAGS  +=-mmacosx-version-min=11.0
LDFLAGS +=-mmacosx-version-min=11.0
USE_RPATH=1
endif
CFLAGS += $(call check_gcc,-std=gnu11,)
CFLAGS += $(CPUFLAGS)
ifeq ($(USE_RPATH),1)
LDFLAGS+=-Wl,-rpath,@executable_path/../Frameworks
endif
ifneq ($(DEBUG),0)
DFLAGS += -DDEBUG
CFLAGS += -g
do_strip=
else
DFLAGS += -DNDEBUG
CFLAGS += -O2
#CFLAGS += -fno-asynchronous-unwind-tables
CFLAGS += $(call check_gcc,-fweb,)
CFLAGS += $(call check_gcc,-frename-registers,)
cmd_strip=$(STRIP) $(1)
define do_strip
	$(call cmd_strip,$(1));
endef
endif

ifeq ($(DO_USERDIRS),1)
CFLAGS += -DDO_USERDIRS=1
endif

ifeq ($(USE_SDL2),1)
CFLAGS += -DUSE_SDL2
endif
CFLAGS += -DGL_SILENCE_DEPRECATION=1

# not relying on sdl-config command and assuming
# /Library/Frameworks/SDL.framework is available
SDL_CFLAGS =-D_GNU_SOURCE=1 -D_THREAD_SAFE
SDL_CFLAGS+=-DSDL_FRAMEWORK -DNO_SDL_CONFIG
ifeq ($(USE_SDL2),1)
SDL_FRAMEWORK_NAME = SDL2
else
SDL_FRAMEWORK_NAME = SDL
endif
# default to our local SDL[2].framework for build
SDL_FRAMEWORK_PATH ?=../MacOSX
ifneq ($(SDL_FRAMEWORK_PATH),)
SDL_LIBS  +=-F$(SDL_FRAMEWORK_PATH)
SDL_CFLAGS+=-F$(SDL_FRAMEWORK_PATH)
endif
SDL_LIBS  +=-Wl,-framework,$(SDL_FRAMEWORK_NAME) -Wl,-framework,Cocoa

NET_LIBS   =

ifneq ($(VORBISLIB),vorbis)
ifneq ($(VORBISLIB),tremor)
$(error Invalid VORBISLIB setting)
endif
endif
ifneq ($(MP3LIB),mpg123)
ifneq ($(MP3LIB),mad)
$(error Invalid MP3LIB setting)
endif
endif
ifeq ($(MP3LIB),mad)
mp3_obj=snd_mp3
lib_mp3dec=-lmad
endif
ifeq ($(MP3LIB),mpg123)
mp3_obj=snd_mpg123
lib_mp3dec=-lmpg123
endif
ifeq ($(VORBISLIB),vorbis)
cpp_vorbisdec=
lib_vorbisdec=-lvorbisfile -lvorbis -logg
endif
ifeq ($(VORBISLIB),tremor)
cpp_vorbisdec=-DVORBIS_USE_TREMOR
lib_vorbisdec=-lvorbisidec -logg
endif

CODECLIBS  =
ifeq ($(USE_CODEC_WAVE),1)
CFLAGS+= -DUSE_CODEC_WAVE
endif
ifeq ($(USE_CODEC_FLAC),1)
CFLAGS+= -DUSE_CODEC_FLAC
CODEC_INC = -I../MacOSX/codecs/include
CODEC_LINK= -L../MacOSX/codecs/lib
CODECLIBS+= -lFLAC
endif
ifeq ($(USE_CODEC_OPUS),1)
CFLAGS+= -DUSE_CODEC_OPUS
CODEC_INC = -I../MacOSX/codecs/include
CODEC_LINK= -L../MacOSX/codecs/lib
CODECLIBS+= -lopusfile -lopus -logg
endif
ifeq ($(USE_CODEC_VORBIS),1)
CFLAGS+= -DUSE_CODEC_VORBIS $(cpp_vorbisdec)
CODEC_INC = -I../MacOSX/codecs/include
CODEC_LINK= -L../MacOSX/codecs/lib
CODECLIBS+= $(lib_vorbisdec)
endif
ifeq ($(USE_CODEC_MP3),1)
CFLAGS+= -DUSE_CODEC_MP3
CODEC_INC = -I../MacOSX/codecs/include
CODEC_LINK= -L../MacOSX/codecs/lib
CODECLIBS+= $(lib_mp3dec)
endif
ifeq ($(USE_CODEC_MIKMOD),1)
CFLAGS+= -DUSE_CODEC_MIKMOD
CODEC_INC = -I../MacOSX/codecs/include
CODEC_LINK= -L../MacOSX/codecs/lib
CODECLIBS+= -lmikmod
endif
ifeq ($(USE_CODEC_XMP),1)
CFLAGS+= -DUSE_CODEC_XMP
CODEC_INC = -I../MacOSX/codecs/include
CODEC_LINK= -L../MacOSX/codecs/lib
CODECLIBS+= -lxmp
endif
ifeq ($(USE_CODEC_MODPLUG),1)
CFLAGS+= -DUSE_CODEC_MODPLUG
CODEC_INC = -I../MacOSX/codecs/include
CODEC_LINK= -L../MacOSX/codecs/lib
CODECLIBS+= -lmodplug
endif
ifeq ($(USE_CODEC_UMX),1)
CFLAGS+= -DUSE_CODEC_UMX
endif
CFLAGS+= $(CODEC_INC)

# QGE (Quantum Game Engine) and Moonlab includes
QGE_INC = -I../../qge -I../../deps/moonlab/src -I../../deps/moonlab/tools
CFLAGS += $(QGE_INC) -DHAS_ACCELERATE=1

COMMON_LIBS= -Wl,-framework,IOKit -Wl,-framework,OpenGL \
	-Wl,-framework,Accelerate -Wl,-framework,Metal \
	-Wl,-framework,Foundation -Wl,-framework,Security \
	-lc++

LIBS = $(COMMON_LIBS) $(NET_LIBS) $(CODEC_LINK) $(CODECLIBS)

# ---------------------------
# objects
# ---------------------------

# QGE (Quantum Game Engine) - all modules
QGE_OBJS = qge_hooks.o qge_init.o qge_rng.o qge_quantum_runtime.o qge_trace.o qge_world.o qge_audio.o qge_render.o qge_vis.o qge_ai.o qge_physics.o qge_metal.o

# Moonlab quantum simulator objects (full set for all QGE modules)
MOONLAB_OBJS = ml_state.o ml_gates.o ml_measurement.o ml_entanglement.o ml_noise.o \
	ml_matrix_math.o ml_entropy.o ml_config.o ml_simd.o ml_accelerate.o ml_gpu_metal.o \
	ml_grover.o ml_qrng.o ml_entropy_pool.o ml_hw_entropy.o ml_health_tests.o \
	ml_bell_test.o ml_bell_alg.o ml_perf_monitor.o ml_memory_align.o ml_gpu_eshkol.o \
	ml_tensor.o ml_tn_state.o ml_tn_gates.o ml_tn_measurement.o ml_svd_compress.o

MUSIC_OBJS= bgmusic.o \
	snd_codec.o \
	snd_flac.o \
	snd_wave.o \
	snd_vorbis.o \
	snd_opus.o \
	$(mp3_obj).o \
	snd_mp3tag.o \
	snd_mikmod.o \
	snd_modplug.o \
	snd_xmp.o \
	snd_umx.o
COMOBJ_SND = snd_dma.o snd_mix.o snd_mem.o snd_quantum.o $(MUSIC_OBJS)
SYSOBJ_SND = snd_sdl.o
SYSOBJ_CDA = cd_sdl.o
SYSOBJ_INPUT = in_sdl.o
SYSOBJ_GL_VID= gl_vidsdl.o
SYSOBJ_NET = net_bsd.o net_udp.o
SYSOBJ_LAUNCHER = AppController.o QuakeArgument.o QuakeArguments.o ScreenInfo.o SDLApplication.o
SYSOBJ_SYS = pl_osx.o sys_sdl_unix.o
SYSOBJ_MAIN= main_sdl.o SDLMain.o

GLOBJS = \
	gl_refrag.o \
	gl_rlight.o \
	gl_rmain.o \
	gl_fog.o \
	gl_rmisc.o \
	r_part.o \
	r_world.o \
	gl_screen.o \
	gl_sky.o \
	gl_warp.o \
	$(SYSOBJ_GL_VID) \
	gl_draw.o \
	image.o \
	gl_texmgr.o \
	gl_mesh.o \
	r_sprite.o \
	r_alias.o \
	r_brush.o \
	gl_model.o

OBJS = strlcat.o \
	strlcpy.o \
	$(GLOBJS) \
	$(QGE_OBJS) \
	$(MOONLAB_OBJS) \
	$(SYSOBJ_INPUT) \
	$(COMOBJ_SND) \
	$(SYSOBJ_SND) \
	$(SYSOBJ_CDA) \
	$(SYSOBJ_NET) \
	net_dgrm.o \
	net_loop.o \
	net_main.o \
	chase.o \
	cl_demo.o \
	cl_input.o \
	cl_main.o \
	cl_parse.o \
	cl_tent.o \
	console.o \
	keys.o \
	menu.o \
	sbar.o \
	view.o \
	wad.o \
	cmd.o \
	common.o \
	miniz.o \
	crc.o \
	cvar.o \
	cfgfile.o \
	host.o \
	host_cmd.o \
	mathlib.o \
	pr_cmds.o \
	pr_edict.o \
	pr_exec.o \
	sv_main.o \
	sv_move.o \
	sv_phys.o \
	sv_user.o \
	world.o \
	zone.o \
	$(SYSOBJ_SYS) \
	$(SYSOBJ_LAUNCHER) $(SYSOBJ_MAIN)

# ---------------------------
# targets / rules
# ---------------------------

.PHONY:	clean debug release

DEFAULT_TARGET = quakespasm
all: $(DEFAULT_TARGET)

# QGE source compile rules
qge_init.o: ../../qge/qge_init.c
	$(CC) $(DFLAGS) -c $(CFLAGS) -o $@ $<

qge_rng.o: ../../qge/qge_rng.c
	$(CC) $(DFLAGS) -c $(CFLAGS) -o $@ $<

qge_quantum_runtime.o: ../../qge/qge_quantum_runtime.c
	$(CC) $(DFLAGS) -c $(CFLAGS) -o $@ $<

qge_trace.o: ../../qge/qge_trace.c
	$(CC) $(DFLAGS) -c $(CFLAGS) -o $@ $<

qge_world.o: ../../qge/qge_world.c
	$(CC) $(DFLAGS) -c $(CFLAGS) -o $@ $<

qge_audio.o: ../../qge/qge_audio.c
	$(CC) $(DFLAGS) -c $(CFLAGS) -o $@ $<

qge_render.o: ../../qge/qge_render.c
	$(CC) $(DFLAGS) -c $(CFLAGS) -o $@ $<

qge_vis.o: ../../qge/qge_vis.c
	$(CC) $(DFLAGS) -c $(CFLAGS) -o $@ $<

qge_ai.o: ../../qge/qge_ai.c
	$(CC) $(DFLAGS) -c $(CFLAGS) -o $@ $<

qge_physics.o: ../../qge/qge_physics.c
	$(CC) $(DFLAGS) -c $(CFLAGS) -o $@ $<

OBJCXX_CFLAGS = $(filter-out -std=gnu11,$(CFLAGS))

qge_metal.o: ../../qge/qge_metal.mm
	$(CC) $(DFLAGS) -c -std=c++17 $(OBJCXX_CFLAGS) -fobjc-arc -o $@ $<

qge_hooks.o: qge_hooks.c
	$(CC) $(DFLAGS) -c $(CFLAGS) $(SDL_CFLAGS) -o $@ $<

# Moonlab quantum simulator compile rules
ml_state.o: ../../deps/moonlab/src/quantum/state.c
	$(CC) $(DFLAGS) -c $(CFLAGS) -o $@ $<

ml_gates.o: ../../deps/moonlab/src/quantum/gates.c
	$(CC) $(DFLAGS) -c $(CFLAGS) -o $@ $<

ml_matrix_math.o: ../../deps/moonlab/src/utils/matrix_math.c
	$(CC) $(DFLAGS) -c $(CFLAGS) -o $@ $<

ml_entropy.o: ../../deps/moonlab/src/utils/entropy.c
	$(CC) $(DFLAGS) -c $(CFLAGS) -o $@ $<

ml_config.o: ../../deps/moonlab/src/utils/config.c
	$(CC) $(DFLAGS) -c $(CFLAGS) -o $@ $<

ml_simd.o: ../../deps/moonlab/src/optimization/simd_ops.c
	$(CC) $(DFLAGS) -c $(CFLAGS) -o $@ $<

ml_accelerate.o: ../../deps/moonlab/src/optimization/accelerate_ops.c
	$(CC) $(DFLAGS) -c $(CFLAGS) -o $@ $<

ml_qrng.o: ../../deps/moonlab/src/applications/qrng.c
	$(CC) $(DFLAGS) -c $(CFLAGS) -o $@ $<

ml_entropy_pool.o: ../../deps/moonlab/src/applications/entropy_pool.c
	$(CC) $(DFLAGS) -c $(CFLAGS) -o $@ $<

ml_hw_entropy.o: ../../deps/moonlab/src/applications/hardware_entropy.c
	$(CC) $(DFLAGS) -c $(CFLAGS) -o $@ $<

ml_health_tests.o: ../../deps/moonlab/src/applications/health_tests.c
	$(CC) $(DFLAGS) -c $(CFLAGS) -o $@ $<

ml_bell_test.o: ../../deps/moonlab/src/applications/bell_test.c
	$(CC) $(DFLAGS) -c $(CFLAGS) -o $@ $<

ml_bell_alg.o: ../../deps/moonlab/src/algorithms/bell_tests.c
	$(CC) $(DFLAGS) -c $(CFLAGS) -o $@ $<

ml_measurement.o: ../../deps/moonlab/src/quantum/measurement.c
	$(CC) $(DFLAGS) -c $(CFLAGS) -o $@ $<

ml_entanglement.o: ../../deps/moonlab/src/quantum/entanglement.c
	$(CC) $(DFLAGS) -c $(CFLAGS) -o $@ $<

ml_noise.o: ../../deps/moonlab/src/quantum/noise.c
	$(CC) $(DFLAGS) -c $(CFLAGS) -o $@ $<

ml_grover.o: ../../deps/moonlab/src/algorithms/grover.c
	$(CC) $(DFLAGS) -c $(CFLAGS) -o $@ $<

ml_gpu_metal.o: ../../deps/moonlab/src/optimization/gpu_metal.mm
	$(CC) $(DFLAGS) -c -std=c++17 $(OBJCXX_CFLAGS) -fobjc-arc -o $@ $<

ml_tensor.o: ../../deps/moonlab/src/algorithms/tensor_network/tensor.c
	$(CC) $(DFLAGS) -c $(CFLAGS) -o $@ $<

ml_tn_state.o: ../../deps/moonlab/src/algorithms/tensor_network/tn_state.c
	$(CC) $(DFLAGS) -c $(CFLAGS) -o $@ $<

ml_tn_gates.o: ../../deps/moonlab/src/algorithms/tensor_network/tn_gates.c
	$(CC) $(DFLAGS) -c $(CFLAGS) -o $@ $<

ml_tn_measurement.o: ../../deps/moonlab/src/algorithms/tensor_network/tn_measurement.c
	$(CC) $(DFLAGS) -c $(CFLAGS) -o $@ $<

ml_svd_compress.o: ../../deps/moonlab/src/algorithms/tensor_network/svd_compress.c
	$(CC) $(DFLAGS) -c $(CFLAGS) -o $@ $<

ml_perf_monitor.o: ../../deps/moonlab/src/utils/performance_monitor.c
	$(CC) $(DFLAGS) -c $(CFLAGS) -o $@ $<

ml_memory_align.o: ../../deps/moonlab/src/optimization/memory_align.c
	$(CC) $(DFLAGS) -c $(CFLAGS) -o $@ $<

ml_gpu_eshkol.o: ../../deps/moonlab/src/optimization/gpu/backends/gpu_eshkol.cpp
	$(CC) $(DFLAGS) -c -std=c++17 $(OBJCXX_CFLAGS) -o $@ $<

%.o:	%.c
	$(CC) $(DFLAGS) -c $(CFLAGS) $(SDL_CFLAGS) -o $@ $<
%.o:	%.m
	$(CC) $(DFLAGS) -c $(CFLAGS) $(SDL_CFLAGS) -o $@ $<
%.o:	../MacOSX/%.m
	$(CC) $(DFLAGS) -c -I../MacOSX $(CFLAGS) $(SDL_CFLAGS) -o $@ $<

quakespasm:	$(OBJS)
	$(LINKER) $(OBJS) $(LDFLAGS) $(LIBS) $(SDL_LIBS) -o $@
	$(call do_strip,$@)

release:	quakespasm
debug:
	$(error Use "make DEBUG=1")

clean:
	$(RM) *.o *.d $(DEFAULT_TARGET)

sinclude $(OBJS:.o=.d)
