#!/usr/bin/env python3
"""Regenerate the Markdown indexes that make every quantum_quake document reachable from README.md.

ICC's `unreferenced-docs` walks real Markdown links (`[text](path)`) from the
README; backticked paths and `../` links are not followed.  So the README links
to INDEX.md (every tracked Markdown document in the repository, grouped by
folder) and docs/ carries a generated docs/INDEX.md beside its hand-written
docs/README.md.  Run after adding documents; commit the result.  Idempotent.
Only tracked files are listed: untracked documents are not living
documentation, and the vendored Moonlab submodule, run artifacts under
diagnostics/ and game data under assets/ are never indexed.

Hand-written folder READMEs (docs/README.md, .icc/README.md) are never
overwritten.

Adapted from the libirrep / GeoRefine / semiclassical_qllm scripts of the same
name (documentation standard 2026-10-03).
"""
from __future__ import annotations
import re, subprocess, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SKIP_DIRS = {'.git', '.worktrees', '.scratch', '__pycache__', 'node_modules', 'build', 'bin',
             'deps', 'diagnostics', 'assets', 'Frameworks', 'QuantumQuake.app', 'QuakeSpasm-SDL2-M1.app'}
# Folders that would get a generated README.md index (recursive).  docs/ and
# .icc/ carry hand-written READMEs, so none is listed.
FOLDERS: list[str] = []
DOCS_INDEX = 'docs/INDEX.md'
# Folder order for the root index (everything else follows alphabetically).
TOP_ORDER = ['docs', '.icc', 'quake', 'tests', 'tools']


def tracked() -> list[str]:
    out = subprocess.run(['git', 'ls-files', '--', '*.md'], cwd=ROOT, capture_output=True, text=True)
    paths = out.stdout.split() if out.returncode == 0 else []
    return [p for p in paths if not any(part in SKIP_DIRS for part in Path(p).parts)]


def title(p: Path) -> str:
    try:
        for line in p.open(errors='replace'):
            if line.startswith('#'):
                return line.lstrip('#').strip()[:110]
    except OSError:
        pass
    return p.stem


def date_key(name: str) -> str:
    m = re.search(r'(20[0-9]{2}-?[01][0-9]-?[0-9]{2})', name)
    return m.group(1).replace('-', '') if m else '0'


def rel_link(from_dir: Path, target: str) -> str:
    """Plain relative link from `from_dir` to repo path `target`, without `../`."""
    return Path(target).relative_to(from_dir).as_posix()


def folder_index(folder: str, known: list[str]) -> str:
    fdir = Path(folder)
    rows = []
    for rel_root in sorted(known):
        p = Path(rel_root)
        if fdir not in p.parents or p == fdir / 'README.md':
            continue
        rows.append(f'- [{rel_link(fdir, rel_root)}]({rel_link(fdir, rel_root)}) — {title(ROOT / rel_root)}')
    body = '\n'.join(rows) if rows else '- (no documents yet)'
    return (f'# {folder}/ index\n\n'
            f'Generated by `scripts/build_doc_indexes.py`: every tracked document under this folder, so ICC and '
            f'readers can reach it from the repository README.\n\n{body}\n')


def docs_index(known: list[str]) -> str:
    rows = []
    for rel_root in sorted(known):
        p = Path(rel_root)
        if p.parent != Path('docs') or p.name in ('README.md', 'INDEX.md'):
            continue
        rows.append(f'- [{p.name}]({p.name}) — {title(ROOT / rel_root)}')
    subs = sorted({Path(k).parts[1] for k in known if Path(k).parts[0] == 'docs' and len(Path(k).parts) > 2})
    sub_rows = []
    for s in subs:
        idx = f'docs/{s}/README.md'
        if idx in known or f'docs/{s}' in FOLDERS:
            sub_rows.append(f'- [{s}/]({s}/README.md)')
        files = [k for k in known if k.startswith(f'docs/{s}/') and k != idx]
        sub_rows.extend(f'- [{rel_link(Path("docs"), k)}]({rel_link(Path("docs"), k)}) — {title(ROOT / k)}'
                        for k in files)
    sub_block = '\n'.join(sub_rows) if sub_rows else '- (none; `docs/claims/`, `docs/media/` and `docs/references/` hold JSON, media and PDF files that are listed in [README.md](README.md))'
    return ('# docs/ index (complete, generated)\n\n'
            'Generated by `scripts/build_doc_indexes.py`: every tracked Markdown document under `docs/`, plus one '
            'link per sub-folder index. The curated reading path is [README.md](README.md). Dated documents '
            'state the status of their date; current status is in the repository README.\n\n'
            '## Sub-folders\n\n' + sub_block + '\n\n'
            '## Documents directly under docs/\n\n' + '\n'.join(rows) + '\n')


def root_index(known: list[str]) -> str:
    groups: dict[str, list[str]] = {}
    for k in known:
        parts = Path(k).parts
        if len(parts) == 1:
            key = '.'
        elif parts[0] == 'docs' and len(parts) > 2:
            key = f'docs/{parts[1]}'
        else:
            key = parts[0]
        groups.setdefault(key, []).append(k)

    def order(key: str) -> tuple:
        top = key.split('/')[0]
        return (0 if key == '.' else 1, TOP_ORDER.index(top) if top in TOP_ORDER else 99, key)

    out = ['# quantum_quake documents index (complete, generated)', '',
           'Generated by `scripts/build_doc_indexes.py`: every tracked Markdown document in the repository, grouped '
           'by folder, so that ICC\'s reachability walk and every reader can reach all of them from the '
           '[README](README.md). Dated documents state the status of their date, not today\'s; for what is '
           'current, read the README and [docs/qge_state_of_development.md](docs/qge_state_of_development.md). '
           'The Moonlab submodule (`deps/moonlab`), run artifacts (`diagnostics/`) and game data (`assets/`) are '
           'not indexed.', '',
           '## Folder indexes', '']
    out += [f'- [{f}/]({f}/README.md)' for f in FOLDERS if (ROOT / f).is_dir()]
    out.append(f'- [docs/]({DOCS_INDEX}) (complete) and [docs/README.md](docs/README.md) (curated)')
    out.append('')
    for key in sorted(groups, key=order):
        files = groups[key]
        if key == '.':
            files.sort(key=lambda k: (date_key(k), k), reverse=True)
            out += ['## Root-level documents', '']
        else:
            files.sort(key=lambda k: (date_key(Path(k).name), k), reverse=True)
            out += [f'## `{key}/`', '']
        out += [f'- [{k}]({k}) — {title(ROOT / k)}' for k in files if k != 'INDEX.md']
        out.append('')
    return '\n'.join(out)


def main() -> int:
    known = tracked()
    written = 0
    (ROOT / 'INDEX.md').write_text(root_index(known), encoding='utf-8'); written += 1
    (ROOT / DOCS_INDEX).write_text(docs_index(known), encoding='utf-8'); written += 1
    for f in FOLDERS:
        folder = ROOT / f
        if not folder.is_dir():
            continue
        (folder / 'README.md').write_text(folder_index(f, known), encoding='utf-8'); written += 1
    print(f'wrote {written} index files over {len(known)} tracked documents')
    return 0


if __name__ == '__main__':
    sys.exit(main())
